## 434_samtrafiken-vechicle-id
* [#434](https://github.com/salgo60/Stockholm_Archipelago_Trail/issues/434)
* denna Notebook [434_samtrafiken-vechicle-id.ipynb](https://github.com/salgo60/Stockholm_Archipelago_Trail/tree/main/Notebook/434_samtrafiken-vechicle-id.ipynb)

In [2]:
import time
import datetime  
start_time = time.time()
start_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
print(f"Started: {start_str}")

Started: 2026-09-11 18:10

In [3]:
%pip install gtfs-realtime-bindings

Requirement already satisfied: gtfs-realtime-bindings in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.2.0)
Requirement already satisfied: protobuf in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from gtfs-realtime-bindings) (7.36.1)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import os
import requests
from google.transit import gtfs_realtime_pb2

API_KEY = os.environ["GTFSSweden3"]

URL = (
    "https://opendata.samtrafiken.se/gtfs-rt-sweden/sl/"
    "VehiclePositionsSweden.pb"
    f"?key={API_KEY}"
)

r = requests.get(URL)
r.raise_for_status()

feed = gtfs_realtime_pb2.FeedMessage()
feed.ParseFromString(r.content)

boats = []

for entity in feed.entity:

    if not entity.HasField("vehicle"):
        continue

    v = entity.vehicle

    boats.append({
        "vehicle_id": v.vehicle.id,
        "vehicle_label": v.vehicle.label,
        "trip_id": v.trip.trip_id,
        "route_id": v.trip.route_id,
        "lat": v.position.latitude,
        "lon": v.position.longitude,
    })

len(boats)

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.3.0) or chardet (7.4.3)/charset_normalizer (3.4.1) doesn't match a supported version!
  warnings.warn(

1643

In [5]:
import pandas as pd

df = pd.DataFrame(boats)

df

,vehicle_id,vehicle_label,trip_id,route_id,lat,lon
0,9031001001004806,,14010000723553084,,59.349709,18.026524
1,9031001004505116,,14010000728996784,,59.743526,18.369452
2,9031001004505580,,14010000728993763,,59.759483,18.698530
3,9031001004500458,,14010000732698072,,59.562397,18.240992
4,9031001001007606,,14010000702283500,,59.316490,18.083599
...,...,...,...,...,...,...
1638,9031001003007210,,14010000723634923,,59.199417,17.626955
1639,9031001003007223,,14010000687991674,,59.201347,17.634489
1640,9031001001007154,,14010000733683009,,59.328728,18.062389
1641,9031001003005319,,14010000725250522,,59.310219,18.160231
1642,9031001001500424,,14010100718635757,,59.239552,18.218264

In [13]:
STATIC_API_KEY = os.environ["GTFSSweden3Static"]

static_url = (
    "https://opendata.samtrafiken.se/"
    "gtfs-sweden/sweden.zip"
    f"?key={STATIC_API_KEY}"
)

In [15]:
print("Finns STATIC_API_KEY:", bool(os.environ.get("STATIC_API_KEY")))

Finns STATIC_API_KEY: False

In [14]:
import requests
import zipfile
import io
import pandas as pd

#print(STATIC_API_KEY)

r = requests.get(static_url)
r.raise_for_status()

z = zipfile.ZipFile(io.BytesIO(r.content))

print(z.namelist())

['routes.txt', 'transfers.txt', 'booking_rules.txt', 'stop_times.txt', 'areas.txt', 'shapes.txt', 'feed_info.txt', 'calendar.txt', 'agency.txt', 'attributions.txt', 'trips.txt', 'calendar_dates.txt', 'stops.txt', 'stop_areas.txt']

In [16]:
print("HTTP:", r.status_code)
print("Bytes:", len(r.content))

HTTP: 200
Bytes: 648163788

In [18]:
stops = pd.read_csv(
    z.open("stops.txt"),
    dtype=str
)

stops[
    stops["stop_name"].str.contains(
        "Fredriksberg", case=False, na=False
    )
][["stop_id", "stop_name"]]

                 stop_id                       stop_name
575                  643           Fredriksberg bussplan
4333                5196  Fredriksberg (Hagby) (Uppsala)
4809                5673  Fredriksberg (Åland) (Uppsala)
6151                7053              Fredriksbergsvägen
8513                9427                    Fredriksberg
...                  ...                             ...
162730  9022050055967002     Burträsk Fredriksbergsvägen
166799  9022050058564001              Fredriksbergsvägen
174892  9022050070086001             Fredriksbergsskolan
177867  9022050071670001              Fredriksbergsvägen
177868  9022050071670002              Fredriksbergsvägen

[79 rows x 2 columns]

In [20]:
boats.append({
    "vehicle_id": v.vehicle.id,
    "vehicle_label": v.vehicle.label,
    "trip_id": v.trip.trip_id,
    "route_id": v.trip.route_id,
    "lat": v.position.latitude,
    "lon": v.position.longitude,
    "current_stop_sequence": v.current_stop_sequence,
    "current_status": v.current_status,
    "timestamp": v.timestamp,
})

In [21]:
df = pd.DataFrame(boats)

In [22]:
df

,vehicle_id,vehicle_label,trip_id,route_id,lat,lon,current_stop_sequence,current_status,timestamp
0,9031001001004806,,14010000723553084,,59.349709,18.026524,NaN,NaN,NaN
1,9031001004505116,,14010000728996784,,59.743526,18.369452,NaN,NaN,NaN
2,9031001004505580,,14010000728993763,,59.759483,18.698530,NaN,NaN,NaN
3,9031001004500458,,14010000732698072,,59.562397,18.240992,NaN,NaN,NaN
4,9031001001007606,,14010000702283500,,59.316490,18.083599,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1639,9031001003007223,,14010000687991674,,59.201347,17.634489,NaN,NaN,NaN
1640,9031001001007154,,14010000733683009,,59.328728,18.062389,NaN,NaN,NaN
1641,9031001003005319,,14010000725250522,,59.310219,18.160231,NaN,NaN,NaN
1642,9031001001500424,,14010100718635757,,59.239552,18.218264,NaN,NaN,NaN
1643,9031001001500424,,14010100718635757,,59.239552,18.218264,0.0,2.0,1.789143e+09

In [24]:
df["route_id"].value_counts().head(30)

route_id
                    1638
9011001054100000       1
9011001056400000       1
9011001056700000       1
9011001055800000       1
9011001078700000       1
9011001055500000       1
Name: count, dtype: int64

In [26]:
routes = pd.read_csv(
    z.open("routes.txt"),
    dtype=str
)

routes.columns

Index(['route_id', 'agency_id', 'route_short_name', 'route_long_name',
       'route_type', 'route_desc'],
      dtype='object')

In [28]:
routes[
    routes["route_short_name"].astype(str).str.strip() == "4"
][[
    "route_id",
    "agency_id",
    "route_short_name",
    "route_long_name"
]]

,route_id,agency_id,route_short_name,route_long_name
7,9011001000400000,505000000000000001,4,NaN
576,9011003000400000,505000000000000003,4,NaN
684,9011004000400000,505000000000000004,4,NaN
713,9011004016700000,505000000000000004,4,NaN
970,9011005020400000,505000000000000005,4,NaN
1060,9011006000400000,505000000000000006,4,NaN
1152,9011007000400000,505000000000000007,4,NaN
1420,9011009000400000,505000000000000009,4,NaN
1439,9011010000400000,505000000000000010,4,NaN
1449,9011010002600000,505000000000000010,4,NaN
1454,9011010004000000,505000000000000010,4,NaN
1509,9011012000400000,505000000000000012,4,Annetorp-Malmö C-Värnhem-Segemölla
1620,9011012040400000,505000000000000012,4,Ystad-Brösarp
1679,9011012060400000,505000000000000012,4,Västergård-Helsingborg C-Elineberg-Humlegården
1692,9011012065400000,505000000000000012,4,Havsbaden - Stationen - Nyhem
1696,9011012066400000,505000000000000012,4,Lingenässkolan-Högskolan-Kristianstad C-Norra ...
1708,9011012073400000,505000000000000012,4,Gunnesbo - Lund C - Norra Fäladen
1717,9011012076400000,505000000000000012,4,Borstahusen - Stationen
1727,9011012078400000,505000000000000012,4,Källesjö - Stationen
1812,9011013130400000,505000000000000013,4,NaN
2777,9011014303400000,505000000000000014,4,NaN
2783,9011014306400000,505000000000000014,4,NaN
2953,9011014480400000,505000000000000014,4,NaN
3031,9011014500400000,505000000000000014,4,NaN
3337,9011014675400000,505000000000000014,4,NaN
3415,9011017000400000,505000000000000017,4,NaN
3545,9011017106400000,505000000000000017,4,NaN
3557,9011018010400000,505000000000000018,4,NaN
3610,9011019000400000,505000000000000019,4,NaN
3667,9011020000400000,505000000000000020,4,NaN
3987,9011021020400000,505000000000000021,4,204
3996,9011021050400000,505000000000000021,4,504
4000,9011021060400000,505000000000000021,4,604
4010,9011021090400000,505000000000000021,4,904
4020,9011022000400000,505000000000000022,4,NaN
4162,9011023000400000,505000000000000023,4,NaN
5256,9011105061500000,505000000000000105,4,NaN
5290,9011114000400000,500000000000000114,4,NaN
5473,9011148060600000,505000000000000148,4,NaN
6179,9011696000400000,505000000000000696,4,NaN
6210,9011706000400000,505000000000000706,4,NaN

In [36]:
agency = pd.read_csv(
    z.open("agency.txt"),
    dtype=str
)

agency.columns
agency[
    agency.astype(str).apply(
        lambda row: row.str.contains(
            "Wax", case=False, na=False
        ).any(),
        axis=1
    )
]

,agency_id,agency_name,agency_url,agency_timezone,agency_lang,agency_fare_url
163,505000000000000606,Waxholmsbolaget Ångfartygs AB,https://www.resrobot.se/,Europe/Stockholm,sv,NaN

In [38]:
trips = pd.read_csv(
    z.open("trips.txt"),
    dtype=str
)

print(trips.shape)
print(trips.columns.tolist())

(350585, 8)
['route_id', 'service_id', 'trip_id', 'trip_headsign', 'trip_short_name', 'direction_id', 'shape_id', 'samtrafiken_internal_trip_number']

In [40]:
trips = pd.read_csv(z.open("trips.txt"), dtype=str)
routes = pd.read_csv(z.open("routes.txt"), dtype=str)

print("trips:", trips.columns.tolist())
print("routes:", routes.columns.tolist())

trips: ['route_id', 'service_id', 'trip_id', 'trip_headsign', 'trip_short_name', 'direction_id', 'shape_id', 'samtrafiken_internal_trip_number']
routes: ['route_id', 'agency_id', 'route_short_name', 'route_long_name', 'route_type', 'route_desc']

In [41]:
trips_routes = trips.merge(
    routes[["route_id", "agency_id"]],
    on="route_id",
    how="left"
)

print(trips_routes.columns.tolist())

['route_id', 'service_id', 'trip_id', 'trip_headsign', 'trip_short_name', 'direction_id', 'shape_id', 'samtrafiken_internal_trip_number', 'agency_id']

In [42]:
wax_trips = trips_routes[
    trips_routes["agency_id"] == "505000000000000606"
]

print("Waxholms-trips:", len(wax_trips))

Waxholms-trips: 0

In [45]:
agency[
    agency["agency_name"].str.contains(
        "Waxholms", case=False, na=False
    )
]

,agency_id,agency_name,agency_url,agency_timezone,agency_lang,agency_fare_url
163,505000000000000606,Waxholmsbolaget Ångfartygs AB,https://www.resrobot.se/,Europe/Stockholm,sv,NaN

In [46]:
routes[
    routes["agency_id"].astype(str).str.contains(
        "505000000000000606",
        na=False
    )
]

Empty DataFrame
Columns: [route_id, agency_id, route_short_name, route_long_name, route_type, route_desc]
Index: []

In [47]:
trips.columns.tolist()

['route_id',
 'service_id',
 'trip_id',
 'trip_headsign',
 'trip_short_name',
 'direction_id',
 'shape_id',
 'samtrafiken_internal_trip_number']

In [48]:
vega = stops[
    stops["stop_name"].str.contains(
        "Vegabrygg", case=False, na=False
    )
][["stop_id", "stop_name"]]

vega

                stop_id    stop_name
12163             13092  Vegabryggan
88879  9022050013092001  Vegabryggan

In [50]:
stop_times = pd.read_csv(
    z.open("stop_times.txt"),
    dtype=str
)

trips = pd.read_csv(
    z.open("trips.txt"),
    dtype=str
)

print("stop_times:", stop_times.shape)
print("trips:", trips.shape)

stop_times: (7836653, 12)
trips: (350585, 8)

In [51]:
live_trips = df.merge(
    trips,
    on=["trip_id", "route_id"],
    how="left"
)

print("Live vehicles:", len(live_trips))

live_trips[
    [
        "vehicle_id",
        "trip_id",
        "route_id",
        "trip_headsign",
        "trip_short_name",
        "samtrafiken_internal_trip_number",
        "lat",
        "lon"
    ]
].head(100)

Live vehicles: 1644

,vehicle_id,trip_id,route_id,trip_headsign,trip_short_name,samtrafiken_internal_trip_number,lat,lon
0,9031001001004806,14010000723553084,,NaN,NaN,NaN,59.349709,18.026524
1,9031001004505116,14010000728996784,,NaN,NaN,NaN,59.743526,18.369452
2,9031001004505580,14010000728993763,,NaN,NaN,NaN,59.759483,18.698530
3,9031001004500458,14010000732698072,,NaN,NaN,NaN,59.562397,18.240992
4,9031001001007606,14010000702283500,,NaN,NaN,NaN,59.316490,18.083599
...,...,...,...,...,...,...,...,...
95,9031001003003571,,9011001054100000,NaN,NaN,NaN,59.422840,17.832609
96,9031001007010740,14010000706734538,,NaN,NaN,NaN,59.299564,18.080257
97,9031001001004560,14010000732600906,,NaN,NaN,NaN,59.396046,17.908394
98,9031001001004810,14010000733600043,,NaN,NaN,NaN,59.339088,18.005598
99,9031001004500457,14010000729352335,,NaN,NaN,NaN,59.533554,18.079464

In [52]:
trips[
    trips["samtrafiken_internal_trip_number"].notna()
][[
    "trip_id",
    "route_id",
    "trip_headsign",
    "trip_short_name",
    "samtrafiken_internal_trip_number"
]].head(20)

,trip_id,route_id,trip_headsign,trip_short_name,samtrafiken_internal_trip_number
0,400000000000005142,9011001000000000,NaN,NaN,2200
1,400000000000005143,9011001000000000,NaN,NaN,2200
2,400000000000005149,9011001000000000,NaN,NaN,2200
3,400000000000005154,9011001000000000,NaN,NaN,2200
4,400000000000005156,9011001000000000,NaN,NaN,2200
5,400000000000005162,9011001000000000,NaN,NaN,2202
6,400000000000005167,9011001000000000,NaN,NaN,2202
7,400000000000005169,9011001000000000,NaN,NaN,2202
8,400000000000005175,9011001000000000,NaN,NaN,2203
9,400000000000005177,9011001000000000,NaN,NaN,2203
10,400000000000005179,9011001000000000,NaN,NaN,2203
11,400000000000005180,9011001000000000,NaN,NaN,2203
12,400000000000005182,9011001000000000,NaN,NaN,2204
13,400000000000005183,9011001000000000,NaN,NaN,2204
14,400000000000005185,9011001000000000,NaN,NaN,2204
15,400000000000005186,9011001000000000,NaN,NaN,2204
16,400000000000005187,9011001000000000,NaN,NaN,2204
17,400000000000005188,9011001000000000,NaN,NaN,2204
18,400000000000005189,9011001000000000,NaN,NaN,2204
19,400000000000005190,9011001000000000,NaN,NaN,2204

In [53]:
print("Live trips som finns i static:", len(live_trips))

Live trips som finns i static: 1644

In [54]:
ferry_routes = routes[
    routes["route_type"].astype(str).str.strip() == "4"
]

print("Antal färjerutter:", len(ferry_routes))

ferry_routes[
    [
        "route_id",
        "agency_id",
        "route_short_name",
        "route_long_name",
        "route_type"
    ]
].head(100)

Antal färjerutter: 0

Empty DataFrame
Columns: [route_id, agency_id, route_short_name, route_long_name, route_type]
Index: []

In [56]:
print(routes.shape)
print(routes.dtypes)
print(routes.head())

(7315, 6)
route_id            object
agency_id           object
route_short_name    object
route_long_name     object
route_type          object
route_desc          object
dtype: object
              route_id           agency_id route_short_name route_long_name  \
0     9011001000000000  505000000000000001               40              SL
1  9011001000000000-41  505000000000000001               41              SL
2  9011001000000000-43  505000000000000001               43              SL
3  9011001000000000-48  505000000000000001               48              SL
4     9011001000100000  505000000000000001                1             NaN

  route_type route_desc
0        106        NaN
1        106        NaN
2        106        NaN
3        106        NaN
4        700        NaN

In [57]:
wax_routes = routes[
    routes["agency_id"] == "505000000000000606"
]

print("Waxholms routes:", len(wax_routes))

wax_routes[
    [
        "route_id",
        "route_short_name",
        "route_long_name",
        "route_type"
    ]
].head(100)

Waxholms routes: 0

Empty DataFrame
Columns: [route_id, route_short_name, route_long_name, route_type]
Index: []

In [58]:
live_trip_ids = set(df["trip_id"].dropna())

matched_trips = trips[
    trips["trip_id"].isin(live_trip_ids)
].copy()

print("Live trip_id som finns i static:", len(matched_trips))

Live trip_id som finns i static: 1565

In [59]:
matched_trips[
    [
        "trip_id",
        "route_id",
        "trip_headsign",
        "trip_short_name",
        "direction_id",
        "samtrafiken_internal_trip_number"
    ]
].head(100)

,trip_id,route_id,trip_headsign,trip_short_name,direction_id,samtrafiken_internal_trip_number
1860,14010000733599687,9011001000100000,NaN,NaN,1,76
1861,14010000733599925,9011001000100000,NaN,NaN,1,78
1862,14010000733600903,9011001000100000,NaN,NaN,1,85
1875,14010000733600082,9011001000100000,NaN,NaN,1,79
1876,14010000733600492,9011001000100000,NaN,NaN,1,82
...,...,...,...,...,...,...
10057,14010100702576815,9011001001100000,NaN,NaN,1,32415
10460,14010100702576793,9011001001100000,NaN,NaN,0,32414
10461,14010100702576973,9011001001100000,NaN,NaN,0,32424
10489,14010100702576703,9011001001100000,NaN,NaN,0,32410
10490,14010100702576883,9011001001100000,NaN,NaN,0,32418

In [60]:
wax_stop_names = stops[
    stops["stop_name"].str.contains(
        "brygga|bryggan",
        case=False,
        na=False
    )
][["stop_id", "stop_name"]]

wax_stop_names.head(100)

      stop_id                stop_name
749       858  Hälleviksstrands brygga
770       879          Rönnängs brygga
880      1020          Östersjö brygga
881      1021         Bromskärs brygga
894      1036            Hotellbryggan
...       ...                      ...
22980   24518       Björkholmen brygga
23164   24706         Järnaviks brygga
23193   24735     Ronneby Brunn brygga
23194   24736      Ronneby Hamn brygga
23195   24737       Ekenäs Karöbryggan

[100 rows x 2 columns]

In [61]:
live_trip_ids = set(df["trip_id"].dropna())

live_stop_times = stop_times[
    stop_times["trip_id"].isin(live_trip_ids)
].copy()

print("Live stop_times:", len(live_stop_times))

Live stop_times: 35782

In [62]:
live_stop_times = live_stop_times.merge(
    stops[["stop_id", "stop_name"]],
    on="stop_id",
    how="left"
)

live_stop_times[
    ["trip_id", "stop_id", "stop_name", "stop_sequence"]
].head(50)

              trip_id           stop_id            stop_name stop_sequence
0   14010000733599687  9022050001174002            Frihamnen             1
1   14010000733599687  9022050009915003       Frihamnsporten             2
2   14010000733599687  9022050010792002      Sehlstedtsgatan             3
3   14010000733599687  9022050009916002      Östhammarsgatan             4
4   14010000733599687  9022050009917002         Rökubbsgatan             5
5   14010000733599687  9022050009918002        Sandhamnsplan             6
6   14010000733599687  9022050012276001               Gärdet             7
7   14010000733599687  9022050012277002     Kampementsbacken             8
8   14010000733599687  9022050009943002       Storskärsgatan             9
9   14010000733599687  9022050012720001           Värtavägen            10
10  14010000733599687  9022050009912001         Jungfrugatan            11
11  14010000733599687  9022050011072002           Nybrogatan            12
12  14010000733599687  9022050009911001          Humlegården            13
13  14010000733599687  9022050009909002            Stureplan            14
14  14010000733599687  9022050011976002       Regeringsgatan            15
15  14010000733599687  9022050012808001             Hötorget            16
16  14010000733599687  9022050001541002       Cityterminalen            17
17  14010000733599687  9022050010790001         Kungsbroplan            18
18  14010000733599687  9022050012262001         Scheelegatan            19
19  14010000733599687  9022050012763001         Celsiusgatan            20
20  14010000733599687  9022050012224001       S:t Eriksgatan            21
21  14010000733599687  9022050009974006         Fridhemsplan            22
22  14010000733599687  9022050009987001      Mariebergsgatan            23
23  14010000733599687  9022050009996002  Fria Ukrainas plats            24
24  14010000733599687  9022050009994001       Wivalliusgatan            25
25  14010000733599687  9022050010815001       Lilla Essingen            26
26  14010000733599687  9022050009995001          Primusgatan            27
27  14010000733599687  9022050012825002            Broparken            28
28  14010000733599687  9022050010023001        Flottbrovägen            29
29  14010000733599687  9022050010025002        Essingetorget            30
30  14010000733599925  9022050001174002            Frihamnen             1
31  14010000733599925  9022050009915003       Frihamnsporten             2
32  14010000733599925  9022050010792002      Sehlstedtsgatan             3
33  14010000733599925  9022050009916002      Östhammarsgatan             4
34  14010000733599925  9022050009917002         Rökubbsgatan             5
35  14010000733599925  9022050009918002        Sandhamnsplan             6
36  14010000733599925  9022050012276001               Gärdet             7
37  14010000733599925  9022050012277002     Kampementsbacken             8
38  14010000733599925  9022050009943002       Storskärsgatan             9
39  14010000733599925  9022050012720001           Värtavägen            10
40  14010000733599925  9022050009912001         Jungfrugatan            11
41  14010000733599925  9022050011072002           Nybrogatan            12
42  14010000733599925  9022050009911001          Humlegården            13
43  14010000733599925  9022050009909002            Stureplan            14
44  14010000733599925  9022050011976002       Regeringsgatan            15
45  14010000733599925  9022050012808001             Hötorget            16
46  14010000733599925  9022050001541002       Cityterminalen            17
47  14010000733599925  9022050010790001         Kungsbroplan            18
48  14010000733599925  9022050012262001         Scheelegatan            19
49  14010000733599925  9022050012763001         Celsiusgatan            20

In [63]:
live_bryggor = live_stop_times[
    live_stop_times["stop_name"]
    .str.contains("brygga|bryggan", case=False, na=False)
]

print("Live trips med brygga:", live_bryggor["trip_id"].nunique())

Live trips med brygga: 103

In [64]:
live_bryggor_routes = (
    live_bryggor
    .merge(
        trips[["trip_id", "route_id"]],
        on="trip_id",
        how="left"
    )
    [["trip_id", "route_id"]]
    .drop_duplicates()
)

print("Antal routes:", len(live_bryggor_routes))

live_bryggor_routes["route_id"].value_counts().head(50)

Antal routes: 103

route_id
9011001005700000         9
9011001043400000         7
9011001071300000         6
9011001074000000         6
9011001070700000         5
9011001086500000         4
9011001062600000         4
9011001063400000         3
9011001043800000         3
9011114001300000         3
9011001023800000         3
9011114000900000         2
9011114000400000         2
9011114000300000         2
9011001084900000         2
9011114001200000         2
9011001084600000         2
9011001083900000         2
9011001085200000         2
9011001063700000         2
9011001063100000         2
9011001030300000         2
9011001043700000         2
9011001043000000-430X    2
9011001042800000-428X    2
9011001035000000         2
9011001034000000         2
9011001063200000         1
9011114000800000         1
9011114002100000         1
9011114001900000         1
9011114001400000         1
9011001030400000         1
9011114001000000         1
9011001031200000         1
9011001086900000         1
9011114000500000         1
9011001063600000         1
9011001042600000         1
9011001043900000         1
9011001046300000         1
9011001063000000         1
9011001068900000         1
9011001008000000         1
9011114002600000         1
Name: count, dtype: int64

In [65]:
boats_candidate = df[
    df["trip_id"].isin(live_bryggor["trip_id"])
].copy()

boats_candidate[
    ["vehicle_id", "trip_id", "route_id", "lat", "lon"]
].drop_duplicates()

            vehicle_id            trip_id route_id        lat        lon
26    9031001001004043  14010000717765671           59.363350  18.123098
29    9031001003005039  14010000734224897           59.164738  18.138391
36    9031001003003111  14010000730094744           59.313225  18.105906
54    9031001003002774  14010000702741272           59.276207  17.918570
56    9031001001507300  14010000701232235           59.257290  17.870081
...                ...                ...      ...        ...        ...
1594  9031001001508556  14010000704331094           59.271370  17.844950
1614  9031001003003129  14010000698085169           59.131569  18.347933
1617  9031001004505522  14010000717579972           59.524532  18.609276
1627  9031001003006198  14010000716065272           59.268326  17.911657
1631  9031001004505129  14010000728998076           59.759426  18.699436

[103 rows x 5 columns]

In [66]:
boats_candidate[
    ["vehicle_id", "lat", "lon"]
].drop_duplicates().sort_values("lat")

            vehicle_id        lat        lon
405   9031001003005115  58.912338  17.949177
821   9031001003005111  58.918350  17.861122
1585  9031001003004962  58.960339  18.022827
183   9031001003004969  58.965591  18.054813
566   9031001000500514  58.982681  18.313002
...                ...        ...        ...
338   9031001004505541  59.744797  18.683748
910   9031001004505542  59.759197  18.698975
1631  9031001004505129  59.759426  18.699436
1575  9031001004505110  59.862484  19.036806
90    9031001004505151  60.145027  18.780094

[103 rows x 3 columns]

In [77]:
trip_info = trips[
    ["trip_id", "route_id", "trip_headsign", "trip_short_name", "direction_id"]
].rename(columns={"route_id": "static_route_id"})

boats_info = boats_candidate.merge(
    trip_info,
    on="trip_id",
    how="left"
)

boats_info[
    [
        "vehicle_id",
        "trip_id",
        "static_route_id",
        "trip_headsign",
        "trip_short_name",
        "lat",
        "lon"
    ]
].drop_duplicates().to_string(index=False)

'      vehicle_id           trip_id       static_route_id trip_headsign trip_short_name       lat       lon\n9031001001004043 14010000717765671      9011001023800000           NaN             NaN 59.363350 18.123098\n9031001003005039 14010000734224897      9011001086500000           NaN             NaN 59.164738 18.138391\n9031001003003111 14010000730094744      9011001043700000           NaN             NaN 59.313225 18.105906\n9031001003002774 14010000702741272      9011001070700000           NaN             NaN 59.276207 17.918570\n9031001001507300 14010000701232235      9011001035000000           NaN             NaN 59.257290 17.870081\n9031001001007602 14010000731134127      9011001005700000           NaN             NaN 59.319675 18.068661\n9031001004505151 14010000728994353      9011001063700000           NaN             NaN 60.145027 18.780094\n9031001003005089 14010000729677480      9011001083900000           NaN             NaN 59.125252 18.316492\n9031001000500502 14010000719255696      9011114000300000           NaN             NaN 59.318031 18.104868\n9031001003004965 14010000716974295      9011001084600000           NaN             NaN 59.108414 18.118473\n9031001003003893 14010000724139337      9011001043400000           NaN             NaN 59.282429 18.557207\n9031001003002775 14010000703775929      9011001070700000           NaN             NaN 59.283234 17.932486\n9031001003003900 14010000701726972      9011001043400000           NaN             NaN 59.315907 18.207209\n9031001001004848 14010000731134863      9011001005700000           NaN             NaN 59.353802 18.099304\n9031001003004969 14010000716973526      9011001084900000           NaN             NaN 58.965591 18.054813\n9031001001007601 14010000731134304      9011001005700000           NaN             NaN 59.320099 18.071346\n9031001003005352 14010000684962183      9011001043900000           NaN             NaN 59.396709 18.449760\n9031001003002778 14010000716068774      9011001071300000           NaN             NaN 59.205269 17.901745\n9031001000500547 14010000729758654      9011114001200000           NaN             NaN 59.463425 18.682562\n9031001008000623 14010000694930879      9011001008000000           NaN             NaN 59.376568 18.092178\n9031001003006047 14010000716974161      9011001084600000           NaN             NaN 59.079769 18.132471\n9031001000500538 14010000729758741      9011114001200000           NaN             NaN 59.359333 18.244658\n9031001003005067 14010000734224518      9011001086500000           NaN             NaN 59.276428 17.908991\n9031001001007616 14010000731133538      9011001005700000           NaN             NaN 59.356956 18.089415\n9031001004505541 14010000728993966      9011001063100000           NaN             NaN 59.744797 18.683748\n9031001003003896 14010000701722944      9011001043400000           NaN             NaN 59.314747 18.097513\n9031001003005115 14010000704155288      9011001085200000           NaN             NaN 58.912338 17.949177\n9031001004505140 14010000728995479      9011001063400000           NaN             NaN 59.651535 18.933516\n9031001001004827 14010000731134753      9011001005700000           NaN             NaN 59.305664 18.080912\n9031001003002769 14010000716066281      9011001071300000           NaN             NaN 59.199203 17.867620\n9031001001506601 14010000729428179      9011001030400000           NaN             NaN 59.293221 17.817480\n9031001003003107 14010000707133181      9011001043800000           NaN             NaN 59.313412 18.444534\n9031001000500681 14010000729753036      9011114000500000           NaN             NaN 59.364632 18.339912\n9031001003002771 14010000703773620      9011001070700000           NaN             NaN 59.202381 17.840034\n9031001003005361 14010000725253159 9011001043000000-430X           NaN             NaN 59.314793 18.096359\n9031001004505115 14010000728997965      9011001063200000           NaN             NaN 59.579277 18.782846\n9031001000500672 14010000728198806      9011114001300000           NaN             NaN 59.422634 18.662094\n9031001003002767 14010000703774723      9011001070700000           NaN             NaN 59.249092 17.865484\n9031001003006188 14010000716067232      9011001071300000           NaN             NaN 59.218910 17.907181\n9031001000500514 14010000719513125      9011114002100000           NaN             NaN 58.982681 18.313002\n9031001000500537 14010000733558348      9011114000300000           NaN             NaN 59.317776 18.099630\n9031001003003897 14010000701724472      9011001043400000           NaN             NaN 59.313229 18.454382\n9031001000500535 14010000729760580      9011114001300000           NaN             NaN 59.319073 18.140722\n9031001003005074 14010000731922989      9011001086500000           NaN             NaN 59.233837 17.925247\n9031001000500679 14010000726055133      9011114000800000           NaN             NaN 59.459938 18.471376\n9031001003003895 14010000701727443      9011001043400000           NaN             NaN 59.359692 18.684227\n9031001004505171 14010000729345141      9011001062600000           NaN             NaN 59.438370 18.563032\n9031001003005110 14010000731922134      9011001086500000           NaN             NaN 59.156902 18.119749\n9031001003007244 14010000715525156      9011001043800000           NaN             NaN 59.350567 18.479546\n9031001003002781 14010000716065673      9011001071300000           NaN             NaN 59.215023 17.955429\n9031001001004829 14010000731133397      9011001005700000           NaN             NaN 59.310421 18.095650\n9031001000500691 14010000728354223      9011114000400000           NaN             NaN 59.402542 18.355778\n9031001003005111 14010000731923040      9011001085200000           NaN             NaN 58.918350 17.861122\n9031001003002780 14010000716064619      9011001074000000           NaN             NaN 59.210049 17.940647\n9031001000500539 14010000729751380      9011114000400000           NaN             NaN 59.402100 18.355913\n9031001004505118 14010000732871123      9011001063400000           NaN             NaN 59.626747 18.903273\n9031001003006201 14010000716066107      9011001074000000           NaN             NaN 59.225990 17.931578\n9031001003005594 14010000716069080      9011001071300000           NaN             NaN 59.219963 17.945724\n9031001004505542 14010000728998525      9011001063400000           NaN             NaN 59.759197 18.698975\n9031001003005077 14010000731923093      9011001083900000           NaN             NaN 59.136967 18.413597\n9031001001507301 14010000701232254      9011001035000000           NaN             NaN 59.271511 17.844700\n9031001004505138 14010000728997889      9011001063000000           NaN             NaN 59.708626 18.845724\n9031001003003097 14010000725251808 9011001042800000-428X           NaN             NaN 59.266216 18.428823\n9031001003002776 14010000716066956      9011001074000000           NaN             NaN 59.273663 17.902889\n9031001000500671 14010000729771779      9011114002600000           NaN             NaN 59.533394 18.575434\n9031001001506905 14010000711673843      9011001034000000           NaN             NaN 59.289841 17.810850\n9031001003002782 14010000716068423      9011001074000000           NaN             NaN 59.226929 17.935844\n9031001000500519 14010000733560460      9011114001900000           NaN             NaN 59.230331 18.361933\n9031001001004821 14010000731134506      9011001005700000           NaN             NaN 59.343655 18.092316\n9031001004505148 14010000728997083      9011001063100000           NaN             NaN 59.732624 18.791620\n9031001000500504 14010000728352190      9011114000900000           NaN             NaN 59.401840 18.355610\n9031001003003875 14010000701726653      9011001043400000           NaN             NaN 59.287331 18.688980\n9031001003002779 14010000716067606      9011001071300000           NaN             NaN 59.210468 17.911711\n9031001003003083 14010000730094209      9011001043700000           NaN             NaN 59.344051 18.480179\n9031001003005355 14010000677028511      9011001042600000           NaN             NaN 59.328297 18.397552\n9031001008500773 14010000724990323      9011114001000000           NaN             NaN 59.475971 18.696913\n9031001003005391 14010000677024030      9011001043800000           NaN             NaN 59.309856 18.132736\n9031001003003892 14010000701724321      9011001043400000           NaN             NaN 59.321453 18.725929\n9031001001004061 14010000702316446      9011001023800000           NaN             NaN 59.363216 18.144487\n9031001000500503 14010000725963231      9011114000900000           NaN             NaN 59.415218 18.353403\n9031001003005433 14010000725251181 9011001042800000-428X           NaN             NaN 59.308662 18.107073\n9031001001508561 14010000733007948      9011001034000000           NaN             NaN 59.340698 17.695900\n9031001003002763 14010000716067691      9011001074000000           NaN             NaN 59.261440 17.878721\n9031001001004502 14010000702315903      9011001023800000           NaN             NaN 59.351501 18.151550\n9031001000500536 14010000729763562      9011114001400000           NaN             NaN 59.398773 18.347485\n9031001004505174 14010000729351697      9011001062600000           NaN             NaN 59.530842 18.434214\n9031001003003099 14010000725251067 9011001043000000-430X           NaN             NaN 59.253006 18.526978\n9031001003005360 14010000684962015      9011001046300000           NaN             NaN 59.340145 18.484818\n9031001001004844 14010000731133917      9011001005700000           NaN             NaN 59.341942 18.085247\n9031001003002757 14010000702741488      9011001070700000           NaN             NaN 59.241043 17.854427\n9031001001506901 14010000701232285      9011001030300000           NaN             NaN 59.331841 17.921721\n9031001006500776 14010000719260685      9011114001300000           NaN             NaN 59.371811 18.611919\n9031001004505533 14010000732695335      9011001062600000           NaN             NaN 59.497002 18.165733\n9031001001004828 14010000731133745      9011001005700000           NaN             NaN 59.307461 18.073709\n9031001004505110 14010000728993884      9011001063600000           NaN             NaN 59.862484 19.036806\n9031001003003957 14010000716894393      9011001068900000           NaN             NaN 59.363354 18.420950\n9031001001507299 14010000729428101      9011001031200000           NaN             NaN 59.383690 17.475451\n9031001003004962 14010000716973805      9011001084900000           NaN             NaN 58.960339 18.022827\n9031001001508556 14010000704331094      9011001030300000           NaN             NaN 59.271370 17.844950\n9031001003003129 14010000698085169      9011001086900000           NaN             NaN 59.131569 18.347933\n9031001004505522 14010000717579972      9011001062600000           NaN             NaN 59.524532 18.609276\n9031001003006198 14010000716065272      9011001074000000           NaN             NaN 59.268326 17.911657\n9031001004505129 14010000728998076      9011001063700000           NaN             NaN 59.759426 18.699436'

In [80]:
import folium

m = folium.Map(
    location=[
        boats_candidate["lat"].mean(),
        boats_candidate["lon"].mean()
    ],
    zoom_start=9
)

for _, row in boats_candidate.drop_duplicates(
    subset=["vehicle_id", "lat", "lon"]
).iterrows():

    popup_text = f"""
    vehicle_id: {row['vehicle_id']}<br>
    lat: {row['lat']}<br>
    lon: {row['lon']}<br>
    trip_id: {row['trip_id']}<br>
    route_id: {row['route_id']}
    """

    folium.Marker(
        location=[row["lat"], row["lon"]],
        popup=folium.Popup(
            popup_text,
            max_width=400
        )
    ).add_to(m)

m

In [8]:
import os
import requests

from google.transit import gtfs_realtime_pb2

API_KEY = os.environ["GTFSSweden3"]

URL = (
    "https://opendata.samtrafiken.se/gtfs-rt/sweden/VehiclePositions.pb"
    f"?key={API_KEY}"
)
URL = (
    "https://opendata.samtrafiken.se//gtfs-rt-sweden/{operator}/VehiclePositionsSweden.pb
    f"?key={API_KEY}"
)

r = requests.get(URL)
r.raise_for_status()

feed = gtfs_realtime_pb2.FeedMessage()
feed.ParseFromString(r.content)

count = 0

for entity in feed.entity:

    if not entity.HasField("vehicle"):
        continue

    v = entity.vehicle

    print("=" * 60)

    print("vehicle.id      :", v.vehicle.id)

    if v.vehicle.label:
        print("vehicle.label   :", v.vehicle.label)

    if v.vehicle.license_plate:
        print("license_plate   :", v.vehicle.license_plate)

    print("trip_id         :", v.trip.trip_id)
    print("route_id        :", v.trip.route_id)

    print("lat/lon         :", v.position.latitude, v.position.longitude)

    count += 1
    if count == 20:
        break
rows = []

for entity in feed.entity:

    if not entity.HasField("vehicle"):
        continue

    vehicle = entity.vehicle

    rows.append({

        "vehicle_id": vehicle.vehicle.id,

        "trip_id":
            vehicle.trip.trip_id
            if vehicle.HasField("trip") else None,

        "latitude":
            vehicle.position.latitude,

        "longitude":
            vehicle.position.longitude,

        "bearing":
            vehicle.position.bearing
            if vehicle.position.HasField("bearing") else None,

        "speed":
            vehicle.position.speed
            if vehicle.position.HasField("speed") else None,

        "timestamp":
            vehicle.timestamp

    })

samtrafiken = pd.DataFrame(rows)

HTTPError: 403 Client Error:  for url: https://opendata.samtrafiken.se/gtfs-rt/sweden/VehiclePositions.pb?key=f2277323909847378fb5951b57fbce03

In [2]:
from zipfile import ZipFile
import pandas as pd

with ZipFile("sweden_api.zip") as z:
    agencies = pd.read_csv(z.open("agency.txt"))

print(agencies)

              agency_id               agency_name                agency_url  \
0                    50  Samtrafiken i Sverige AB  https://www.resrobot.se/
1    500000000000000043          Trafikverket RDB  https://www.resrobot.se/
2    500000000000000107           Vy flygbussarna  https://www.resrobot.se/
3    500000000000000109                       109  https://www.resrobot.se/
4    500000000000000110                       110  https://www.resrobot.se/
..                  ...                       ...                       ...
244  505000000000000764          Tåg i Bergslagen  https://www.resrobot.se/
245  505000000000000765              Krösatåg KLT  https://www.resrobot.se/
246  505000000000000766                   Norrtåg  https://www.resrobot.se/
247  505000000000000767                 Vy Tåg AB  https://www.resrobot.se/
248  505000000000000768               LT X-trafik  https://www.resrobot.se/

      agency_timezone agency_lang  agency_fare_url
0    Europe/Stockholm          sv              NaN
1    Europe/Stockholm          sv              NaN
2    Europe/Stockholm          sv              NaN
3    Europe/Stockholm          sv              NaN
4    Europe/Stockholm          sv              NaN
..                ...         ...              ...
244  Europe/Stockholm          sv              NaN
245  Europe/Stockholm          sv              NaN
246  Europe/Stockholm          sv              NaN
247  Europe/Stockholm          sv              NaN
248  Europe/Stockholm          sv              NaN

[249 rows x 6 columns]

In [3]:
from zipfile import ZipFile
import pandas as pd

with ZipFile("sweden_api.zip") as z:
    agencies = pd.read_csv(z.open("agency.txt"))
    routes = pd.read_csv(z.open("routes.txt"))

# Leta efter Waxholmsbolaget
waxholm = agencies[
    agencies["agency_name"].str.contains("wax", case=False, na=False)
]

print(waxholm)

wax_routes = routes.merge(agencies, on="agency_id")

wax_routes = wax_routes[
    wax_routes["agency_name"].str.contains("wax", case=False, na=False)
]

print(wax_routes[[
    "route_id",
    "route_short_name",
    "route_long_name",
    "route_type",
    "agency_name"
]])

              agency_id                    agency_name  \
159  505000000000000606  Waxholmsbolaget Ångfartygs AB

                   agency_url   agency_timezone agency_lang  agency_fare_url
159  https://www.resrobot.se/  Europe/Stockholm          sv              NaN
Empty DataFrame
Columns: [route_id, route_short_name, route_long_name, route_type, agency_name]
Index: []

In [5]:
from zipfile import ZipFile
import pandas as pd

with ZipFile("sweden_api.zip") as z:
    routes = pd.read_csv(z.open("routes.txt"))

print(routes.columns.tolist())

print("\nAntal routes:", len(routes))

print("\nAgency IDs som används:")

print(routes["agency_id"].value_counts())

['route_id', 'agency_id', 'route_short_name', 'route_long_name', 'route_type', 'route_desc']

Antal routes: 7575

Agency IDs som används:
agency_id
505000000000000014    1672
505000000000000100     576
500000000000000790     567
505000000000000001     534
505000000000000174     383
                      ...
505000000000000120       1
500000000000000154       1
505000000000000145       1
505000000000000140       1
505000000000000111       1
Name: count, Length: 81, dtype: int64

In [6]:
from zipfile import ZipFile
import pandas as pd

with ZipFile("sweden_api.zip") as z:
    agencies = pd.read_csv(z.open("agency.txt"))
    routes = pd.read_csv(z.open("routes.txt"))

routes = routes.merge(agencies, on="agency_id", how="left")

# Visa alla färjelinjer
ferries = routes[routes["route_type"] == 4]

print(f"Antal färjelinjer: {len(ferries)}")

print(
    ferries[
        [
            "agency_id",
            "agency_name",
            "route_id",
            "route_short_name",
            "route_long_name",
        ]
    ].head(50)
)

Antal färjelinjer: 0
Empty DataFrame
Columns: [agency_id, agency_name, route_id, route_short_name, route_long_name]
Index: []

In [7]:
from zipfile import ZipFile
import pandas as pd

with ZipFile("sweden_api.zip") as z:
    routes = pd.read_csv(z.open("routes.txt"))

print(routes["route_type"].value_counts().sort_index())

route_type
100       66
101      459
103      123
105       20
106     2871
401        7
700     3363
714       12
900       30
1000     103
1501     521
Name: count, dtype: int64

In [8]:
from zipfile import ZipFile
import pandas as pd

with ZipFile("sweden_api.zip") as z:
    routes = pd.read_csv(z.open("routes.txt"))

for rt in sorted(routes.route_type.unique()):
    print("\n========== route_type", rt, "==========")
    cols = ["route_short_name", "route_long_name"]

    if "route_desc" in routes.columns:
        cols.append("route_desc")

    print(routes[routes.route_type == rt][cols].head(20).to_string(index=False))

========== route_type 100 ==========
route_short_name                                   route_long_name  route_desc
            1079                                          Krösatåg         NaN
            1085                                          Krösatåg         NaN
            1086                                          Krösatåg         NaN
            1087                                          Krösatåg         NaN
            1088                                          Krösatåg         NaN
            1089                                          Krösatåg         NaN
              70                                               NaN         NaN
              71                                               NaN         NaN
              74                                               NaN         NaN
           Anrop                                               270         NaN
               1                                                SJ         NaN
             344                                               NaN         NaN
           10344                                               344         NaN
           60344                                               344         NaN
             802   Ø Karlskrona - Kristianstad - Malmö - København         NaN
             803 Ø Kalmar - Växjö - Hässleholm - Malmö - København         NaN
             804        Ø Göteborg-Halmstad-Helsingborg-Malmö-Købe         NaN
             805                 Ø Helsingborg - Malmö - København         NaN
             806     Ø Insatsturer Helsingborg - Malmö - København         NaN
               1                                       Lennakatten         NaN

========== route_type 101 ==========
route_short_name route_long_name  route_desc
              89             NaN         NaN
             400             NaN         NaN
             419             NaN         NaN
             420             NaN         NaN
             421             NaN         NaN
             422             NaN         NaN
             423             NaN         NaN
             424             NaN         NaN
           10424             424         NaN
             425             NaN         NaN
             426             NaN         NaN
             427             NaN         NaN
             428             NaN         NaN
             429             NaN         NaN
             430             NaN         NaN
             431             NaN         NaN
             432             NaN         NaN
             433             NaN         NaN
             434             NaN         NaN
             435             NaN         NaN

========== route_type 103 ==========
route_short_name route_long_name  route_desc
              10             NaN         NaN
           60010              10         NaN
           70010              10         NaN
              11             NaN         NaN
           60011              11         NaN
           70011              11         NaN
           80011              11         NaN
              12             NaN         NaN
              13             NaN         NaN
              14             NaN         NaN
              15             NaN         NaN
              16             NaN         NaN
           60016              16         NaN
              17             NaN         NaN
           60017              17         NaN
              18             NaN         NaN
              19             NaN         NaN
           60019              19         NaN
              20             NaN         NaN
              21             NaN         NaN

========== route_type 105 ==========
route_short_name route_long_name  route_desc
               1             NaN         NaN
               2             NaN         NaN
              70             NaN         NaN
           60070              70         NaN
           70070              70         NaN
              71             NaN         NaN
           60071              71         NaN
           70071              71         NaN
              91             NaN         NaN
              92             NaN         NaN
              93             NaN         NaN
              94             NaN         NaN
             345             NaN         NaN
           13471            3471         NaN
              24             NaN         NaN
              25             NaN         NaN
             300             NaN         NaN
             301             NaN         NaN
             304             NaN         NaN
             305             NaN         NaN

========== route_type 106 ==========
route_short_name route_long_name  route_desc
              40              SL         NaN
              41              SL         NaN
              43              SL         NaN
              48              SL         NaN
            8702  Östgötapendeln         NaN
           18702  Östgötapendeln         NaN
           18771  Östgötapendeln         NaN
           18777  Östgötapendeln         NaN
           18789  Östgötapendeln         NaN
           18802  Östgötapendeln         NaN
           18803  Östgötapendeln         NaN
           18806  Östgötapendeln         NaN
           18807  Östgötapendeln         NaN
           18816  Östgötapendeln         NaN
           18817  Östgötapendeln         NaN
           18819  Östgötapendeln         NaN
           18820  Östgötapendeln         NaN
           18823  Östgötapendeln         NaN
           18824  Östgötapendeln         NaN
           18825  Östgötapendeln         NaN

========== route_type 401 ==========
route_short_name route_long_name  route_desc
              10      Blå linjen         NaN
              11      Blå linjen         NaN
              13     Röda linjen         NaN
              14     Röda linjen         NaN
              17    Gröna linjen         NaN
              18    Gröna linjen         NaN
              19    Gröna linjen         NaN

========== route_type 700 ==========
route_short_name route_long_name  route_desc
               1             NaN         NaN
               2             NaN         NaN
               3             NaN         NaN
               4             NaN         NaN
               5             NaN         NaN
               6             NaN         NaN
              50             NaN         NaN
              53             NaN         NaN
              54             NaN         NaN
              55             NaN         NaN
              56             NaN         NaN
              57             NaN         NaN
              61             NaN         NaN
              65             NaN         NaN
              66             NaN         NaN
              67             NaN         NaN
              69             NaN         NaN
              71             NaN         NaN
              72             NaN         NaN
              74             NaN         NaN

========== route_type 714 ==========
route_short_name route_long_name  route_desc
           80662             662         NaN
           80663             663         NaN
           80667             667         NaN
           80668             668         NaN
           80670             670         NaN
           80675             675         NaN
           80678             678         NaN
           80679             679         NaN
           80682             682         NaN
           80684             684         NaN
           80685             685         NaN
           80688             688         NaN

========== route_type 900 ==========
route_short_name         route_long_name  route_desc
               7            Spårväg city         NaN
              12            Nockebybanan         NaN
              21            Lidingöbanan         NaN
              25            Saltsjöbanan         NaN
              26            Saltsjöbanan         NaN
              27            Kårstalinjen         NaN
              28        Österskärslinjen         NaN
             28S        Österskärslinjen         NaN
             28V        Österskärslinjen         NaN
              29        Näsbyparkslinjen         NaN
              30               Tvärbanan         NaN
              31               Tvärbanan         NaN
               2                     NaN         NaN
               3                     NaN         NaN
               1 Lund C - ESS (spårvagn)         NaN
               1                     NaN         NaN
               2                     NaN         NaN
               3                     NaN         NaN
               4                     NaN         NaN
               5                     NaN         NaN

========== route_type 1000 ==========
route_short_name route_long_name  route_desc
              80             NaN         NaN
             80X             NaN         NaN
              82 Djurgårdsfärjan         NaN
              84             NaN         NaN
              89             NaN         NaN
             900     Gräsöfärjan         NaN
             775 Skärgårdstrafik         NaN
           Dessi     Färja Dessi         NaN
             908             NaN         NaN
             910             NaN         NaN
             911             NaN         NaN
             912             NaN         NaN
             913             NaN         NaN
             914             NaN         NaN
             915             NaN         NaN
             920             NaN         NaN
             921             NaN         NaN
             922             NaN         NaN
             930             NaN         NaN
             931             NaN         NaN

========== route_type 1501 ==========
route_short_name                            route_long_name  route_desc
             164                                        NaN         NaN
             306                                        NaN         NaN
             401                                        NaN         NaN
             483                                        NaN         NaN
             513                                        NaN         NaN
             562                                        NaN         NaN
             129                                        NaN         NaN
             126                         126 Visingsöbussen         NaN
             983                Ersättningtrafik Tjustbanan         NaN
             984          Ersättningstrafik Stångådalsbanan         NaN
              50        Klagshamnsverket - Klagshamn - Pile         NaN
              51                          Skumparp - Hyllie         NaN
              56                       Lindängen - Käglinge         NaN
             101    Trulstorp - Mossheddinge - Staffanstorp         NaN
             102                        Hjärup-Staffanstorp         NaN
             108               Gårdstånga - Odarslöv - Lund         NaN
             127 Staffanstorp - Nordanå - Särslöv - Tottarp         NaN
             135             Lomma Kyrka - Lomma Busstation         NaN
             140                             Oxie - Svedala         NaN
             143        Svedala - V Kärrstorp - V Ingelstad         NaN

In [9]:
from zipfile import ZipFile
import pandas as pd

with ZipFile("sweden_api.zip") as z:
    routes = pd.read_csv(z.open("routes.txt"))

ferries = routes[routes.route_type == 1000]

print(ferries[[
    "route_id",
    "agency_id",
    "route_short_name",
    "route_long_name"
]].to_string(index=False))

            route_id          agency_id route_short_name                   route_long_name
    9011001008000000 505000000000000001               80                               NaN
9011001008000000-80X 505000000000000001              80X                               NaN
    9011001008200000 505000000000000001               82                   Djurgårdsfärjan
    9011001008400000 505000000000000001               84                               NaN
    9011001008900000 505000000000000001               89                               NaN
    9011003090000000 505000000000000003              900                       Gräsöfärjan
    9011005077500000 505000000000000005              775                   Skärgårdstrafik
    9011008098500000 505000000000000008            Dessi                       Färja Dessi
    9011010090800000 505000000000000010              908                               NaN
    9011010091000000 505000000000000010              910                               NaN
    9011010091100000 505000000000000010              911                               NaN
    9011010091200000 505000000000000010              912                               NaN
    9011010091300000 505000000000000010              913                               NaN
    9011010091400000 505000000000000010              914                               NaN
    9011010091500000 505000000000000010              915                               NaN
    9011010092000000 505000000000000010              920                               NaN
    9011010092100000 505000000000000010              921                               NaN
    9011010092200000 505000000000000010              922                               NaN
    9011010093000000 505000000000000010              930                               NaN
    9011010093100000 505000000000000010              931                               NaN
    9011010093200000 505000000000000010              932                               NaN
    9011010093300000 505000000000000010              933                               NaN
    9011010094000000 505000000000000010              940                               NaN
    9011010190800000 505000000000000010             1908                               NaN
    9011010191400000 505000000000000010              914                               NaN
    9011010191600000 505000000000000010             1916                               NaN
    9011010191800000 505000000000000010             1918                               NaN
    9011010891000000 505000000000000010             8910                               NaN
    9011012059900000 505000000000000012              Båt                       Barum - Ivö
    9011014484700000 505000000000000014              847                               NaN
    9011014487900000 505000000000000014              879                               NaN
    9011014489000000 505000000000000014              890                               NaN
    9011014489900000 505000000000000014              899                               NaN
    9011014528100000 505000000000000014              281                               NaN
    9011014528200000 505000000000000014              282                               NaN
    9011014528300000 505000000000000014              283                               NaN
    9011014528400000 505000000000000014              284                               NaN
    9011014528500000 505000000000000014              285                               NaN
    9011014528600000 505000000000000014              286                               NaN
    9011014528700000 505000000000000014              287                               NaN
    9011014629600000 505000000000000014              296                               NaN
    9011014632600000 505000000000000014              326                               NaN
    9011014636100000 505000000000000014              361                               NaN
    9011014636200000 505000000000000014              362                               NaN
    9011014638100000 505000000000000014              381                               NaN
    9011017009000000 505000000000000017               90                               NaN
    9011017009100000 505000000000000017               91                               NaN
    9011017009200000 505000000000000017               92                               NaN
    9011017009300000 505000000000000017               93                               NaN
    9011017009400000 505000000000000017               94                               NaN
    9011017009600000 505000000000000017               96                               NaN
    9011017009900000 505000000000000017               99                               NaN
    9011103019900000 505000000000000103            Färja                               199
    9011106001100000 505000000000000106               DG                               NaN
    9011106001200000 505000000000000106               DG                               NaN
    9011108076600000 505000000000000108              Båt       Båt till Ven Landskrona-Ven
    9011114000200000 500000000000000114                2                               NaN
    9011114000300000 500000000000000114                3                               NaN
    9011114000400000 500000000000000114                4                               NaN
    9011114000500000 500000000000000114                5                               NaN
    9011114000700000 500000000000000114                7                               NaN
    9011114000800000 500000000000000114                8                               NaN
    9011114000900000 500000000000000114                9                               NaN
    9011114001000000 500000000000000114               10                               NaN
    9011114001100000 500000000000000114               11                               NaN
    9011114001200000 500000000000000114               12                               NaN
    9011114001300000 500000000000000114               13                               NaN
    9011114001400000 500000000000000114               14                               NaN
9011114001400000-14X 500000000000000114              14X                               NaN
    9011114001500000 500000000000000114               15                               NaN
    9011114001600000 500000000000000114               16                               NaN
    9011114001700000 500000000000000114               17                               NaN
    9011114001800000 500000000000000114               18                               NaN
    9011114001900000 500000000000000114               19                               NaN
    9011114002000000 500000000000000114               20                               NaN
    9011114002100000 500000000000000114               21                               NaN
    9011114002200000 500000000000000114               22                               NaN
    9011114002300000 500000000000000114               23                               NaN
    9011114002400000 500000000000000114               24                               NaN
    9011114002500000 500000000000000114               25                               NaN
    9011114002600000 500000000000000114               26                               NaN
    9011114002700000 500000000000000114               27                               NaN
    9011114002800000 500000000000000114               28                               NaN
    9011114002900000 500000000000000114               29                               NaN
    9011114003000000 500000000000000114               30                               NaN
    9011114003100000 500000000000000114               31                               NaN
    9011141002900000 505000000000000141            DESSI                               NaN
    9011141003000000 505000000000000141           EMELIE                               NaN
    9011145000100000 505000000000000145           Tärnan                               NaN
    9011147000100000 505000000000000147                1 Stockholm-Vaxholm-Grinda-Sandhamn
    9011147001100000 505000000000000147               11  Hop on Hop off båt Göteborg 2026
    9011158010000000 505000000000000158               UA                    Uddevallaturen
    9011158020000000 505000000000000158              200                     Lyckornaturen
    9011158040000000 505000000000000158              400                     Lysekilsturen
    9011168000100000 505000000000000168                1                    Sjöstadslinjen
    9011173010100000 505000000000000173                1       Sandhamnslinjen SOMMAR 2026
    9011608094100000 505000000000000608              941                     Vaxholm-Rindö
    9011608094300000 505000000000000608              943                      Adelsö-Munsö
    9011635032200000 505000000000000635              Båt                  Marstrandsfärjan
    9011639029700000 505000000000000639              Båt                        Hönöfärjan
    9011639029800000 505000000000000639              Båt                      Björköfärjan
    9011639029900000 505000000000000639              Båt                       Nordöfärjan
    9011639038700000 505000000000000639              Båt                  Svanesundsfärjan

In [10]:
from zipfile import ZipFile
import pandas as pd

with ZipFile("sweden_api.zip") as z:
    agencies = pd.read_csv(z.open("agency.txt"))

print(
    agencies[
        agencies.agency_id == 500000000000000114
    ]
)

            agency_id agency_name                agency_url   agency_timezone  \
5  500000000000000114         114  https://www.resrobot.se/  Europe/Stockholm

  agency_lang  agency_fare_url
5          sv              NaN

In [11]:
from zipfile import ZipFile
import pandas as pd
from google.transit import gtfs_realtime_pb2

# ----- Läs GTFS static -----

with ZipFile("sweden_api.zip") as z:
    trips = pd.read_csv(
        z.open("trips.txt"),
        dtype={"trip_id": str, "route_id": str},
        low_memory=False,
    )

    routes = pd.read_csv(
        z.open("routes.txt"),
        dtype={"route_id": str},
    )

trips = trips[["trip_id", "route_id"]]
routes = routes[["route_id", "route_short_name", "route_long_name", "route_type"]]

# ----- Läs VehiclePositions -----

feed = gtfs_realtime_pb2.FeedMessage()

with open("VehiclePositions.pb", "rb") as f:
    feed.ParseFromString(f.read())

rows = []

for entity in feed.entity:

    if not entity.HasField("vehicle"):
        continue

    v = entity.vehicle
    rows.append({
        "vehicle_id": str(v.vehicle.id),
        "trip_id": str(v.trip.trip_id),
    })

vehicles = pd.DataFrame(rows)

# ----- Koppla ihop -----

df = (
    vehicles
      .merge(trips, on="trip_id", how="left")
      .merge(routes, on="route_id", how="left")
)

print(df.sort_values("route_short_name").head(200))

df.to_csv("vehicle_routes.csv", index=False)

            vehicle_id            trip_id          route_id route_short_name  \
683   9031001001004023  14010000686337262  9011001000100000                1
893   9031001001004106  14010000686338040  9011001000100000                1
245   9031001001004020  14010000686336803  9011001000100000                1
1044  9031001001004003  14010000717717327  9011001000100000                1
1278  9031001001004019  14010000724503990  9011001000100000                1
...                ...                ...               ...              ...
18    9031001003002738  14010000689190197  9011001016700000              167
1012  9031001003005589  14010000689193126  9011001016700000              167
875   9031001003005531  14010000689191094  9011001016700000              167
159   9031001003002745  14010000689193924  9011001016700000              167
65    9031001002500043  14010100722680590  9011001001700000               17

     route_long_name  route_type
683              NaN       700.0
893              NaN       700.0
245              NaN       700.0
1044             NaN       700.0
1278             NaN       700.0
...              ...         ...
18               NaN       700.0
1012             NaN       700.0
875              NaN       700.0
159              NaN       700.0
65      Gröna linjen       401.0

[200 rows x 6 columns]

In [12]:
ferries = df[df["route_type"] == 1000].copy()

ferries = ferries.sort_values(["route_short_name", "vehicle_id"])

print(ferries[
    ["vehicle_id",
     "route_short_name",
     "route_id"]
])

ferries.to_csv("ferries.csv", index=False)

            vehicle_id route_short_name              route_id
1035  9031001000500504               11      9011114001100000
246   9031001000500538               12      9011114001200000
713   9031001000500539               12      9011114001200000
1220  9031001000500520               13      9011114001300000
216   9031001000500547               13      9011114001300000
1335  9031001006500776               13      9011114001300000
1292  9031001000500536               14      9011114001400000
1363  9031001000500540               14      9011114001400000
390   9031001000500546               14      9011114001400000
436   9031001000500681               14      9011114001400000
379   9031001000500736               14      9011114001400000
274   9031001000500513               16      9011114001600000
923   9031001000500549               16      9011114001600000
986   9031001000500519               17      9011114001700000
188   9031001008500737               17      9011114001700000
479   9031001000500537               18      9011114001800000
563   9031001000500679               18      9011114001800000
475   9031001000500514               21      9011114002100000
830   9031001000500751               21      9011114002100000
884   9031001000500671               26      9011114002600000
463   9031001000500672               27      9011114002700000
1229  9031001000500550               28      9011114002800000
1249  9031001000500577               29      9011114002900000
96    9031001000500555                3      9011114000300000
354   9031001000500796               30      9011114003000000
681   9031001008000622               80      9011001008000000
225   9031001008000623               80      9011001008000000
1020  9031001008000625               80      9011001008000000
964   9031001008000628               80      9011001008000000
1082  9031001008000633               80      9011001008000000
508   9031001008000634               80      9011001008000000
38    9031001008000636               80      9011001008000000
298   9031001008000700               80      9011001008000000
493   9031001008000630              80X  9011001008000000-80X
217   9031001008000635              80X  9011001008000000-80X
864   9031001007500529               82      9011001008200000
1260  9031001007500530               82      9011001008200000
14    9031001007500531               82      9011001008200000
735   9031001007500651               84      9011001008400000
121   9031001007500664               84      9011001008400000
755   9031001008000627               89      9011001008900000
1200  9031001000500503                9      9011114000900000
873   9031001000500523                9      9011114000900000
326   9031001000500548                9      9011114000900000

In [13]:
route3 = ferries[ferries["route_short_name"] == "3"]
route3

,vehicle_id,trip_id,route_id,route_short_name,route_long_name,route_type
96,9031001000500555,14010000726426404,9011114000300000,3,NaN,1000.0

In [15]:
from zipfile import ZipFile
import pandas as pd

with ZipFile("sweden_api.zip") as z:
    stop_times = pd.read_csv(z.open("stop_times.txt"))

stop_times.head()

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,timepoint,pickup_booking_rule_id,drop_off_booking_rule_id
0,400000000000009622,04:08:00,04:08:00,9022050001617006,1,Uppsala central,0,1,NaN,1,NaN,NaN
1,400000000000009622,04:10:00,04:10:00,9022050001618003,2,Uppsala central,0,0,NaN,1,NaN,NaN
2,400000000000009622,04:15:00,04:15:00,9022050000759010,3,Uppsala central,0,0,NaN,1,NaN,NaN
3,400000000000009622,04:18:00,04:18:00,9022050000781003,4,Uppsala central,0,0,NaN,1,NaN,NaN
4,400000000000009622,04:21:00,04:21:00,9022050011423003,5,Uppsala central,0,0,NaN,1,NaN,NaN

In [16]:
trip_id = "14010000726426404"

trip = (
    stop_times[stop_times.trip_id == trip_id]
    .sort_values("stop_sequence")
)

trip

Empty DataFrame
Columns: [trip_id, arrival_time, departure_time, stop_id, stop_sequence, stop_headsign, pickup_type, drop_off_type, shape_dist_traveled, timepoint, pickup_booking_rule_id, drop_off_booking_rule_id]
Index: []

In [17]:
with ZipFile("sweden_api.zip") as z:
    stops = pd.read_csv(z.open("stops.txt"))

stops.head()

,stop_id,stop_name,stop_lat,stop_lon,location_type,parent_station,platform_code
0,1,Stockholm Centralstation,59.331537,18.054943,1,NaN,NaN
1,2,Göteborg Centralstation,57.709299,11.973659,1,NaN,NaN
2,3,Malmö Centralstation,55.608777,13.000216,1,NaN,NaN
3,4,Alvesta station,56.898911,14.556790,1,NaN,NaN
4,5,Uppsala Centralstation,59.857739,17.647666,1,NaN,NaN

In [18]:
trip_stops = (
    stop_times
      .merge(stops, on="stop_id")
      .sort_values(["trip_id","stop_sequence"])
)

trip_stops.head(20)

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,timepoint,pickup_booking_rule_id,drop_off_booking_rule_id,stop_name,stop_lat,stop_lon,location_type,parent_station,platform_code
1548097,14010000509102393,23:47:00,23:47:00,9022050010353004,1,Södertälje centrum,3,1,0.00,1,NaN,NaN,Hovsjöskolan,59.175203,17.603916,0,10353.0,4
1548098,14010000509102393,23:47:59,23:47:59,9022050011476002,2,Södertälje centrum,3,3,295.62,0,NaN,NaN,Hovsjö centrum,59.176716,17.608072,0,11476.0,2
1548099,14010000509102393,23:49:36,23:49:36,9022050008498002,3,Södertälje centrum,3,3,959.14,0,NaN,NaN,Vibergen,59.178788,17.614674,0,8498.0,2
1548100,14010000509102393,23:50:55,23:50:55,9022050011475002,4,Södertälje centrum,3,3,1526.70,0,NaN,NaN,Saltskogs centrum,59.178910,17.620653,0,11475.0,2
1548101,14010000509102393,23:51:40,23:51:40,9022050008497002,5,Södertälje centrum,3,3,1821.35,0,NaN,NaN,Förmansvägen,59.181006,17.623194,0,8497.0,2
1548102,14010000509102393,23:53:23,23:53:23,9022050010354002,6,Södertälje centrum,3,3,2533.20,0,NaN,NaN,Scania centralkontor,59.183046,17.631200,0,10354.0,2
1548103,14010000509102393,23:55:19,23:55:19,9022050008484002,7,Södertälje centrum,3,3,3489.52,0,NaN,NaN,Värdsholmsgatan,59.187481,17.631763,0,8484.0,2
1548104,14010000509102393,23:58:00,23:58:00,9022050012578008,8,Södertälje centrum,1,3,4306.45,1,NaN,NaN,Södertälje centrum,59.192071,17.627843,0,12578.0,F
1548105,14010000509110182,24:17:00,24:17:00,9022050010353004,1,Södertälje centrum,3,1,0.00,1,NaN,NaN,Hovsjöskolan,59.175203,17.603916,0,10353.0,4
1548106,14010000509110182,24:17:59,24:17:59,9022050011476002,2,Södertälje centrum,3,3,295.62,0,NaN,NaN,Hovsjö centrum,59.176716,17.608072,0,11476.0,2
1548107,14010000509110182,24:19:36,24:19:36,9022050008498002,3,Södertälje centrum,3,3,959.14,0,NaN,NaN,Vibergen,59.178788,17.614674,0,8498.0,2
1548108,14010000509110182,24:20:55,24:20:55,9022050011475002,4,Södertälje centrum,3,3,1526.70,0,NaN,NaN,Saltskogs centrum,59.178910,17.620653,0,11475.0,2
1548109,14010000509110182,24:21:40,24:21:40,9022050008497002,5,Södertälje centrum,3,3,1821.35,0,NaN,NaN,Förmansvägen,59.181006,17.623194,0,8497.0,2
1548110,14010000509110182,24:23:23,24:23:23,9022050010354002,6,Södertälje centrum,3,3,2533.20,0,NaN,NaN,Scania centralkontor,59.183046,17.631200,0,10354.0,2
1548111,14010000509110182,24:25:19,24:25:19,9022050008484002,7,Södertälje centrum,3,3,3489.52,0,NaN,NaN,Värdsholmsgatan,59.187481,17.631763,0,8484.0,2
1548112,14010000509110182,24:28:00,24:28:00,9022050012578008,8,Södertälje centrum,1,3,4306.45,1,NaN,NaN,Södertälje centrum,59.192071,17.627843,0,12578.0,F
1548169,14010000509110290,24:47:00,24:47:00,9022050010353004,1,Södertälje centrum,3,1,0.00,1,NaN,NaN,Hovsjöskolan,59.175203,17.603916,0,10353.0,4
1548170,14010000509110290,24:47:59,24:47:59,9022050011476002,2,Södertälje centrum,3,3,295.62,0,NaN,NaN,Hovsjö centrum,59.176716,17.608072,0,11476.0,2
1548171,14010000509110290,24:49:36,24:49:36,9022050008498002,3,Södertälje centrum,3,3,959.14,0,NaN,NaN,Vibergen,59.178788,17.614674,0,8498.0,2
1548172,14010000509110290,24:50:55,24:50:55,9022050011475002,4,Södertälje centrum,3,3,1526.70,0,NaN,NaN,Saltskogs centrum,59.178910,17.620653,0,11475.0,2

In [19]:
with ZipFile("sweden_api.zip") as z:
    trips = pd.read_csv(z.open("trips.txt"))
    routes = pd.read_csv(z.open("routes.txt"))

route3 = routes[routes.route_short_name=="3"]

route3

/var/folders/fd/md6r13sj0wsbg_6_xl160d300000gn/T/ipykernel_52670/4080688729.py:2: DtypeWarning: Columns (0,4) have mixed types. Specify dtype option on import or set low_memory=False.
  trips = pd.read_csv(z.open("trips.txt"))

,route_id,agency_id,route_short_name,route_long_name,route_type,route_desc
6,9011001000300000,505000000000000001,3,NaN,700,NaN
536,9011003000300000,505000000000000003,3,NaN,700,NaN
649,9011004000300000,505000000000000004,3,NaN,700,NaN
672,9011004014300000,505000000000000004,3,NaN,700,NaN
673,9011004016300000,505000000000000004,3,NaN,700,NaN
680,9011004018300000,505000000000000004,3,NaN,700,NaN
887,9011005000300000,505000000000000005,3,NaN,900,NaN
912,9011005020300000,505000000000000005,3,NaN,700,NaN
997,9011006000300000,505000000000000006,3,NaN,700,NaN
1087,9011007000300000,505000000000000007,3,NaN,700,NaN
1102,9011007003400000,505000000000000007,3,NaN,700,NaN
1358,9011009000300000,505000000000000009,3,NaN,700,NaN
1376,9011010000300000,505000000000000010,3,NaN,700,NaN
1386,9011010003000000,505000000000000010,3,NaN,700,NaN
1406,9011010041400000,505000000000000010,3,NaN,700,NaN
1456,9011010700300000,505000000000000010,3,NaN,700,NaN
1463,9011010703000000,505000000000000010,3,NaN,700,NaN
1481,9011012000300000,505000000000000012,3,Ringlinjen,700,NaN
1584,9011012040300000,505000000000000012,3,Kristianstad - Simrishamn,700,NaN
1655,9011012065300000,505000000000000012,3,Pomona - Stationen - Kroneslätt,700,NaN
1659,9011012066300000,505000000000000012,3,Möllebacken-Kristianstad C-Viby,700,NaN
1664,9011012067300000,505000000000000012,3,Tormestorp - Centralen - Läreda,700,NaN
1670,9011012073300000,505000000000000012,3,Nöbbelöv - Lund C - Linero,700,NaN
1679,9011012076300000,505000000000000012,3,Stationen - Skeppsbron,700,NaN
1689,9011012078300000,505000000000000012,3,Stationen - Backaskolan - Stationen,700,NaN
1767,9011013130300000,505000000000000013,3,NaN,700,NaN
2745,9011014200300000,505000000000000014,3,NaN,700,NaN
2823,9011014303300000,505000000000000014,3,NaN,700,NaN
3003,9011014480300000,505000000000000014,3,NaN,700,NaN
3084,9011014500300000,505000000000000014,3,NaN,900,NaN
3259,9011014627300000,505000000000000014,3,NaN,700,NaN
3262,9011014628300000,505000000000000014,3,NaN,700,NaN
3288,9011014634300000,505000000000000014,3,NaN,700,NaN
3356,9011014657300000,505000000000000014,3,NaN,700,NaN
3371,9011014662300000,505000000000000014,3,NaN,700,NaN
3392,9011014675300000,505000000000000014,3,NaN,700,NaN
3470,9011017000300000,505000000000000017,3,NaN,700,NaN
3611,9011017106300000,505000000000000017,3,NaN,700,NaN
3622,9011018010300000,505000000000000018,3,NaN,700,NaN
3671,9011019000300000,505000000000000019,3,NaN,700,NaN
3729,9011020000300000,505000000000000020,3,NaN,700,NaN
3992,9011021020300000,505000000000000021,3,203,700,NaN
3999,9011021040300000,505000000000000021,3,403,700,NaN
4002,9011021050300000,505000000000000021,3,503,700,NaN
4006,9011021060300000,505000000000000021,3,603,700,NaN
4016,9011021090300000,505000000000000021,3,903,700,NaN
4025,9011022000300000,505000000000000022,3,NaN,700,NaN
4281,9011024000300000,505000000000000024,3,NaN,700,NaN
5391,9011105061300000,505000000000000105,3,NaN,700,NaN
5426,9011114000300000,500000000000000114,3,NaN,1000,NaN
5629,9011148060300000,505000000000000148,3,NaN,700,NaN
6444,9011696000300000,505000000000000696,3,NaN,700,NaN
6475,9011706000300000,505000000000000706,3,NaN,700,NaN

In [20]:
print(stop_times.columns.tolist())
print(trips.columns.tolist())

['trip_id', 'arrival_time', 'departure_time', 'stop_id', 'stop_sequence', 'stop_headsign', 'pickup_type', 'drop_off_type', 'shape_dist_traveled', 'timepoint', 'pickup_booking_rule_id', 'drop_off_booking_rule_id']
['route_id', 'service_id', 'trip_id', 'trip_headsign', 'trip_short_name', 'direction_id', 'shape_id', 'samtrafiken_internal_trip_number']

In [21]:
route3 = trips[trips.route_id == "9011114000300000"]

route3[
    [
        "trip_id",
        "trip_short_name",
        "samtrafiken_internal_trip_number",
        "service_id",
        "direction_id"
    ]
].sort_values(
    "samtrafiken_internal_trip_number"
)

,trip_id,trip_short_name,samtrafiken_internal_trip_number,service_id,direction_id
406594,14010000726445298,NaN,300,811,1
406606,14010000729656166,NaN,301,1647,1
406608,14010000729656390,NaN,301,645,1
406612,14010000729656226,NaN,301,3954,1
406588,14010000726426339,NaN,301,414,1
...,...,...,...,...,...
406592,14010000726426187,NaN,379,637,1
406624,14010000721785463,NaN,380,637,0
406596,14010000729172203,NaN,381,637,1
406619,14010000721785443,NaN,382,637,0
406643,14010000726938597,NaN,396,637,0

In [23]:
route3.to_csv("route3.csv")

In [24]:
route3 = trips[trips["route_id"] == "9011114000300000"]

print("Trips:", len(route3))

route3[
    [
        "trip_id",
        "service_id",
        "direction_id",
        "trip_short_name",
        "samtrafiken_internal_trip_number"
    ]
].sort_values(
    ["direction_id", "samtrafiken_internal_trip_number"]
)

Trips: 72

,trip_id,service_id,direction_id,trip_short_name,samtrafiken_internal_trip_number
406629,14010000725132390,414,0,NaN,302
406646,14010000729656520,677,0,NaN,302
406639,14010000725132327,379,0,NaN,304
406635,14010000725132367,414,0,NaN,306
406645,14010000729656545,677,0,NaN,306
...,...,...,...,...,...
406576,14010000725131569,637,1,NaN,373
406607,14010000729656203,637,1,NaN,375
406598,14010000729656180,637,1,NaN,377
406592,14010000726426187,637,1,NaN,379
406596,14010000729172203,637,1,NaN,381

In [25]:
trip305 = route3[
    route3["samtrafiken_internal_trip_number"] == 305
]

trip305

,route_id,service_id,trip_id,trip_headsign,trip_short_name,direction_id,shape_id,samtrafiken_internal_trip_number
406616,9011114000300000,810,14010100726445298,NaN,NaN,1,6014010000721783677,305

In [26]:
trip_id = trip305.iloc[0]["trip_id"]

(
    stop_times[stop_times.trip_id == trip_id]
      .merge(
          stops[["stop_id", "stop_name"]],
          on="stop_id"
      )
      .sort_values("stop_sequence")
)[[
    "stop_sequence",
    "stop_name",
    "arrival_time",
    "pickup_booking_rule_id",
    "drop_off_booking_rule_id"
]]

,stop_sequence,stop_name,arrival_time,pickup_booking_rule_id,drop_off_booking_rule_id
0,1,Grenadjärbryggan,06:45:00,NaN,NaN
1,2,Ramsöberg,06:50:00,NaN,NaN
2,3,Knutsholmen,07:00:00,NaN,NaN
3,4,Skogsö södra,07:05:00,NaN,NaN
4,5,Hästholmen,07:07:00,NaN,NaN
5,6,Skogsö udde,07:10:00,NaN,NaN
6,7,Norra Lagnö,07:20:00,NaN,NaN

In [27]:
trip305 = (
    stop_times
      .query("trip_id == @trip_id")
      .merge(stops,on="stop_id")
      .sort_values("stop_sequence")
)

trip305

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,timepoint,pickup_booking_rule_id,drop_off_booking_rule_id,stop_name,stop_lat,stop_lon,location_type,parent_station,platform_code
0,14010100726445298,06:45:00,06:45:00,9022050013101001,1,Gåshaga via Norra Lagnö,3,1,0.00,1,NaN,NaN,Grenadjärbryggan,59.390903,18.433926,0,13101.0,1
1,14010100726445298,06:50:00,06:50:00,9022050013093001,2,Gåshaga via Norra Lagnö,3,3,1301.19,1,NaN,NaN,Ramsöberg,59.384360,18.418887,0,13093.0,1
2,14010100726445298,07:00:00,07:00:00,9022050013094001,3,Gåshaga via Norra Lagnö,3,3,2786.40,1,NaN,NaN,Knutsholmen,59.376485,18.435003,0,13094.0,1
3,14010100726445298,07:05:00,07:05:00,9022050013096001,4,Gåshaga via Norra Lagnö,3,3,4300.70,1,NaN,NaN,Skogsö södra,59.368334,18.442454,0,13096.0,1
4,14010100726445298,07:07:00,07:07:00,9022050013095001,5,Gåshaga via Norra Lagnö,3,3,4772.60,1,NaN,NaN,Hästholmen,59.365172,18.441042,0,13095.0,1
5,14010100726445298,07:10:00,07:10:00,9022050013097001,6,Gåshaga via Norra Lagnö,3,3,5260.95,1,NaN,NaN,Skogsö udde,59.366367,18.433891,0,13097.0,1
6,14010100726445298,07:20:00,07:20:00,9022050013001001,7,Gåshaga via Norra Lagnö,1,3,7544.44,1,NaN,NaN,Norra Lagnö,59.355297,18.411543,0,13001.0,1

In [28]:
trip305["pdf_flag"] = None

In [37]:
with ZipFile("sweden_api.zip") as z: 
     files = sorted(z.namelist())
for f in files:
    if "booking" in f.lower():
        print(f)

booking_rules.txt

In [38]:
from zipfile import ZipFile
import pandas as pd

with ZipFile("sweden_api.zip") as z:
    booking_rules = pd.read_csv(z.open("booking_rules.txt"))

booking_rules.head(100)

,booking_rule_id,booking_type,prior_notice_duration_min,prior_notice_last_day,prior_notice_last_time,message,phone_number
0,14010000696807824,1,120.0,NaN,NaN,Resan måste beställas på sl.se senast 2 timmar...,NaN
1,14010000696809111,1,120.0,NaN,NaN,Resan måste beställas på sl.se senast 2 timmar...,NaN
2,14010000696811043,1,120.0,NaN,NaN,Resan måste beställas på sl.se senast 2 timmar...,NaN
3,14010000697510764,1,120.0,NaN,NaN,Resan måste beställas på sl.se senast 2 timmar...,NaN
4,14010000697638602,1,120.0,NaN,NaN,Resan måste beställas på sl.se senast 2 timmar...,NaN
...,...,...,...,...,...,...,...
95,40000000000000013,2,NaN,1.0,20:00:00,Måste förbeställas senast kl. 20:00 dagen före...,0771-22 40 00
96,40000000000000014,2,NaN,0.0,20:00:00,Måste förbeställas senast kl. 20:00 samma dag ...,0771-22 40 00
97,40000000000000015,2,NaN,1.0,20:00:00,Måste förbeställas senast kl. 20:00 dagen före...,0771-22 40 00
98,40000000000000016,2,NaN,0.0,20:00:00,Måste förbeställas senast kl. 20:00 samma dag ...,0771-22 40 00
99,40000000000000017,2,NaN,0.0,20:00:00,Måste förbeställas senast kl. 20:00 samma dag ...,0771-22 40 00

In [39]:
trip = (
    stop_times[stop_times.trip_id == trip_id]
      .merge(
          stops[["stop_id", "stop_name"]],
          on="stop_id"
      )
      .merge(
          booking_rules,
          left_on="pickup_booking_rule_id",
          right_on="booking_rule_id",
          how="left",
          suffixes=("","_pickup")
      )
      .sort_values("stop_sequence")
)

trip[
    [
        "stop_sequence",
        "stop_name",
        "arrival_time",
        "pickup_type",
        "pickup_booking_rule_id",
        "prior_notice_duration_min",
        "message"
    ]
]

,stop_sequence,stop_name,arrival_time,pickup_type,pickup_booking_rule_id,prior_notice_duration_min,message
0,1,Grenadjärbryggan,06:45:00,3,NaN,NaN,NaN
1,2,Ramsöberg,06:50:00,3,NaN,NaN,NaN
2,3,Knutsholmen,07:00:00,3,NaN,NaN,NaN
3,4,Skogsö södra,07:05:00,3,NaN,NaN,NaN
4,5,Hästholmen,07:07:00,3,NaN,NaN,NaN
5,6,Skogsö udde,07:10:00,3,NaN,NaN,NaN
6,7,Norra Lagnö,07:20:00,1,NaN,NaN,NaN

In [40]:
trip = (
    stop_times[stop_times.trip_id == trip_id]
      .merge(
          stops[["stop_id", "stop_name"]],
          on="stop_id"
      )
      .merge(
          booking_rules,
          left_on="pickup_booking_rule_id",
          right_on="booking_rule_id",
          how="left",
          suffixes=("","_pickup")
      )
      .sort_values("stop_sequence")
)

trip[
    [
        "stop_sequence",
        "stop_name",
        "arrival_time",
        "pickup_type",
        "pickup_booking_rule_id",
        "prior_notice_duration_min",
        "message"
    ]
]

,stop_sequence,stop_name,arrival_time,pickup_type,pickup_booking_rule_id,prior_notice_duration_min,message
0,1,Grenadjärbryggan,06:45:00,3,NaN,NaN,NaN
1,2,Ramsöberg,06:50:00,3,NaN,NaN,NaN
2,3,Knutsholmen,07:00:00,3,NaN,NaN,NaN
3,4,Skogsö södra,07:05:00,3,NaN,NaN,NaN
4,5,Hästholmen,07:07:00,3,NaN,NaN,NaN
5,6,Skogsö udde,07:10:00,3,NaN,NaN,NaN
6,7,Norra Lagnö,07:20:00,1,NaN,NaN,NaN

In [41]:
print(len(booking_rules))

5485

In [47]:
booking_rules[
    [
        "prior_notice_duration_min",
        "prior_notice_last_day",
        "prior_notice_last_time", 
        "phone_number"
    ]
].drop_duplicates()

,prior_notice_duration_min,prior_notice_last_day,prior_notice_last_time,phone_number
0,120.0,NaN,NaN,NaN
35,0.0,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN
83,NaN,1.0,20:00:00,0771-22 40 00
85,NaN,0.0,20:00:00,0771-22 40 00
90,120.0,NaN,NaN,0771-22 40 00
217,NaN,1.0,18:00:00,NaN
445,NaN,1.0,04:00:00,NaN
803,60.0,NaN,NaN,NaN
990,60.0,NaN,NaN,0771-75 07 00
1001,NaN,1.0,22:00:00,0771-75 07 00
1401,180.0,NaN,NaN,NaN
1474,5.0,NaN,NaN,NaN
1555,NaN,1.0,17:00:00,NaN
2007,30.0,NaN,NaN,NaN
2022,NaN,1.0,22:30:00,NaN
3973,NaN,1.0,19:00:00,NaN
4154,NaN,1.0,16:00:00,0771-82 00 83
4793,NaN,1.0,17:00:00,0771-10 01 10
4889,60.0,NaN,NaN,0771-10 01 10

In [50]:
print("Antal olika regler",len(booking_rules[
    [
        "prior_notice_duration_min",
        "prior_notice_last_day",
        "prior_notice_last_time",
    ]
].drop_duplicates()))

Antal olika regler 16

In [49]:
print("Antal olika regler",len(booking_rules[
    [
        "prior_notice_duration_min",
        "prior_notice_last_day",
        "prior_notice_last_time",
        "phone_number"
    ]
].drop_duplicates()))

Antal olika regler 20

In [46]:
print("Antal olika regler",booking_rules.drop_duplicates())

Antal olika regler          booking_rule_id  booking_type  prior_notice_duration_min  \
0      14010000696807824             1                      120.0
1      14010000696809111             1                      120.0
2      14010000696811043             1                      120.0
3      14010000697510764             1                      120.0
4      14010000697638602             1                      120.0
...                  ...           ...                        ...
5480  250000000000000154             2                        NaN
5481  250000000000000155             2                        NaN
5482  250000000000000156             2                        NaN
5483  250000000000000157             2                        NaN
5484  250000000000000158             2                        NaN

      prior_notice_last_day prior_notice_last_time  \
0                       NaN                    NaN
1                       NaN                    NaN
2                       NaN                    NaN
3                       NaN                    NaN
4                       NaN                    NaN
...                     ...                    ...
5480                    1.0               17:00:00
5481                    1.0               17:00:00
5482                    1.0               17:00:00
5483                    1.0               17:00:00
5484                    1.0               17:00:00

                                                message   phone_number
0     Resan måste beställas på sl.se senast 2 timmar...            NaN
1     Resan måste beställas på sl.se senast 2 timmar...            NaN
2     Resan måste beställas på sl.se senast 2 timmar...            NaN
3     Resan måste beställas på sl.se senast 2 timmar...            NaN
4     Resan måste beställas på sl.se senast 2 timmar...            NaN
...                                                 ...            ...
5480  Turen är Efterfrågestyrd och beställs senast 1...  0771-10 01 10
5481  Turen är Efterfrågestyrd och beställs senast 1...  0771-10 01 10
5482  Turen är Efterfrågestyrd och beställs senast 1...  0771-10 01 10
5483  Turen är Efterfrågestyrd och beställs senast 1...  0771-10 01 10
5484  Turen är Efterfrågestyrd och beställs senast 1...  0771-10 01 10

[5485 rows x 7 columns]