## 434_samtrafiken-vechicle-id
* [#434](https://github.com/salgo60/Stockholm_Archipelago_Trail/issues/434)
* denna Notebook [434_samtrafiken-vechicle-id.ipynb](https://github.com/salgo60/Stockholm_Archipelago_Trail/tree/main/Notebook/434_samtrafiken-vechicle-id.ipynb)

In [1]:
import time
import datetime  
start_time = time.time()
start_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
print(f"Started: {start_str}")

Started: 2026-09-12 09:04

In [2]:
%pip install gtfs-realtime-bindings

Requirement already satisfied: gtfs-realtime-bindings in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.2.0)
Requirement already satisfied: protobuf in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from gtfs-realtime-bindings) (7.36.1)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import os
import requests
from google.transit import gtfs_realtime_pb2

API_KEY = os.environ["GTFSSweden3"]

URL = (
    "https://opendata.samtrafiken.se/gtfs-rt-sweden/sl/"
    "VehiclePositionsSweden.pb"
    f"?key={API_KEY}"
)

r = requests.get(URL)
r.raise_for_status()

feed = gtfs_realtime_pb2.FeedMessage()
feed.ParseFromString(r.content)

boats = []

for entity in feed.entity:

    if not entity.HasField("vehicle"):
        continue

    v = entity.vehicle

    boats.append({
        "vehicle_id": v.vehicle.id,
        "vehicle_label": v.vehicle.label,
        "trip_id": v.trip.trip_id,
        "route_id": v.trip.route_id,
        "lat": v.position.latitude,
        "lon": v.position.longitude,
    })

len(boats)

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.3.0) or chardet (7.4.3)/charset_normalizer (3.4.1) doesn't match a supported version!
  warnings.warn(

648

In [4]:
import pandas as pd

df = pd.DataFrame(boats)

df

,vehicle_id,vehicle_label,trip_id,route_id,lat,lon
0,9031001001004806,,14010000721637124,,59.308216,18.079399
1,9031001004505580,,14010000729011536,,59.741592,18.599932
2,9031001003005037,,14010000731930696,,59.228245,17.998379
3,9031001003005052,,14010100731930960,,59.194607,18.189713
4,9031001007011770,,14010000706740822,,59.342743,17.969767
...,...,...,...,...,...,...
643,9031001001506964,,14010000729438489,,59.319500,17.866070
644,9031001003005075,,14010000708183850,,59.171284,18.179632
645,9031001001004132,,14010000731567613,,59.380405,17.882540
646,9031001001007154,,,,59.309856,18.096180
647,9031001003005319,,14010000715530544,,59.355595,18.603558

In [5]:
STATIC_API_KEY = os.environ["GTFSSweden3Static"]

static_url = (
    "https://opendata.samtrafiken.se/"
    "gtfs-sweden/sweden.zip"
    f"?key={STATIC_API_KEY}"
)

In [6]:
print("Finns STATIC_API_KEY:", bool(os.environ.get("STATIC_API_KEY")))

Finns STATIC_API_KEY: False

In [7]:
import requests
import zipfile
import io
import pandas as pd

#print(STATIC_API_KEY)

r = requests.get(static_url)
r.raise_for_status()

z = zipfile.ZipFile(io.BytesIO(r.content))

print(z.namelist())

['stops.txt', 'calendar.txt', 'booking_rules.txt', 'shapes.txt', 'feed_info.txt', 'areas.txt', 'trips.txt', 'attributions.txt', 'transfers.txt', 'routes.txt', 'calendar_dates.txt', 'stop_times.txt', 'agency.txt', 'stop_areas.txt']

In [8]:
print("HTTP:", r.status_code)
print("Bytes:", len(r.content))

HTTP: 200
Bytes: 652212318

In [9]:
stops = pd.read_csv(
    z.open("stops.txt"),
    dtype=str
)

stops[
    stops["stop_name"].str.contains(
        "Fredriksberg", case=False, na=False
    )
][["stop_id", "stop_name"]]

                 stop_id                       stop_name
575                  643           Fredriksberg bussplan
4333                5196  Fredriksberg (Hagby) (Uppsala)
4809                5673  Fredriksberg (Åland) (Uppsala)
6151                7053              Fredriksbergsvägen
8513                9427                    Fredriksberg
...                  ...                             ...
162731  9022050055967002     Burträsk Fredriksbergsvägen
166800  9022050058564001              Fredriksbergsvägen
174893  9022050070086001             Fredriksbergsskolan
177868  9022050071670001              Fredriksbergsvägen
177869  9022050071670002              Fredriksbergsvägen

[79 rows x 2 columns]

In [10]:
boats.append({
    "vehicle_id": v.vehicle.id,
    "vehicle_label": v.vehicle.label,
    "trip_id": v.trip.trip_id,
    "route_id": v.trip.route_id,
    "lat": v.position.latitude,
    "lon": v.position.longitude,
    "current_stop_sequence": v.current_stop_sequence,
    "current_status": v.current_status,
    "timestamp": v.timestamp,
})

In [11]:
df = pd.DataFrame(boats)

In [12]:
df

,vehicle_id,vehicle_label,trip_id,route_id,lat,lon,current_stop_sequence,current_status,timestamp
0,9031001001004806,,14010000721637124,,59.308216,18.079399,NaN,NaN,NaN
1,9031001004505580,,14010000729011536,,59.741592,18.599932,NaN,NaN,NaN
2,9031001003005037,,14010000731930696,,59.228245,17.998379,NaN,NaN,NaN
3,9031001003005052,,14010100731930960,,59.194607,18.189713,NaN,NaN,NaN
4,9031001007011770,,14010000706740822,,59.342743,17.969767,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
644,9031001003005075,,14010000708183850,,59.171284,18.179632,NaN,NaN,NaN
645,9031001001004132,,14010000731567613,,59.380405,17.882540,NaN,NaN,NaN
646,9031001001007154,,,,59.309856,18.096180,NaN,NaN,NaN
647,9031001003005319,,14010000715530544,,59.355595,18.603558,NaN,NaN,NaN
648,9031001003005319,,14010000715530544,,59.355595,18.603558,0.0,2.0,1.789197e+09

In [13]:
df["route_id"].value_counts().head(30)

route_id
                    647
9011001040100000      1
9011001020100000      1
Name: count, dtype: int64

In [14]:
routes = pd.read_csv(
    z.open("routes.txt"),
    dtype=str
)

routes.columns

Index(['route_id', 'agency_id', 'route_short_name', 'route_long_name',
       'route_type', 'route_desc'],
      dtype='object')

In [15]:
routes[
    routes["route_short_name"].astype(str).str.strip() == "4"
][[
    "route_id",
    "agency_id",
    "route_short_name",
    "route_long_name"
]]

,route_id,agency_id,route_short_name,route_long_name
7,9011001000400000,505000000000000001,4,NaN
578,9011003000400000,505000000000000003,4,NaN
686,9011004000400000,505000000000000004,4,NaN
715,9011004016700000,505000000000000004,4,NaN
972,9011005020400000,505000000000000005,4,NaN
1062,9011006000400000,505000000000000006,4,NaN
1154,9011007000400000,505000000000000007,4,NaN
1422,9011009000400000,505000000000000009,4,NaN
1441,9011010000400000,505000000000000010,4,NaN
1451,9011010002600000,505000000000000010,4,NaN
1456,9011010004000000,505000000000000010,4,NaN
1510,9011012000400000,505000000000000012,4,Annetorp-Malmö C-Värnhem-Segemölla
1621,9011012040400000,505000000000000012,4,Ystad-Brösarp
1680,9011012060400000,505000000000000012,4,Västergård-Helsingborg C-Elineberg-Humlegården
1693,9011012065400000,505000000000000012,4,Havsbaden - Stationen - Nyhem
1697,9011012066400000,505000000000000012,4,Lingenässkolan-Högskolan-Kristianstad C-Norra ...
1709,9011012073400000,505000000000000012,4,Gunnesbo - Lund C - Norra Fäladen
1718,9011012076400000,505000000000000012,4,Borstahusen - Stationen
1728,9011012078400000,505000000000000012,4,Källesjö - Stationen
1813,9011013130400000,505000000000000013,4,NaN
2778,9011014303400000,505000000000000014,4,NaN
2784,9011014306400000,505000000000000014,4,NaN
2954,9011014480400000,505000000000000014,4,NaN
3032,9011014500400000,505000000000000014,4,NaN
3338,9011014675400000,505000000000000014,4,NaN
3416,9011017000400000,505000000000000017,4,NaN
3546,9011017106400000,505000000000000017,4,NaN
3558,9011018010400000,505000000000000018,4,NaN
3611,9011019000400000,505000000000000019,4,NaN
3668,9011020000400000,505000000000000020,4,NaN
3988,9011021020400000,505000000000000021,4,204
3997,9011021050400000,505000000000000021,4,504
4001,9011021060400000,505000000000000021,4,604
4011,9011021090400000,505000000000000021,4,904
4021,9011022000400000,505000000000000022,4,NaN
4163,9011023000400000,505000000000000023,4,NaN
5257,9011105061500000,505000000000000105,4,NaN
5291,9011114000400000,500000000000000114,4,NaN
5477,9011148060600000,505000000000000148,4,NaN
6188,9011696000400000,505000000000000696,4,NaN
6219,9011706000400000,505000000000000706,4,NaN

In [16]:
agency = pd.read_csv(
    z.open("agency.txt"),
    dtype=str
)

agency.columns
agency[
    agency.astype(str).apply(
        lambda row: row.str.contains(
            "Wax", case=False, na=False
        ).any(),
        axis=1
    )
]

,agency_id,agency_name,agency_url,agency_timezone,agency_lang,agency_fare_url
163,505000000000000606,Waxholmsbolaget Ångfartygs AB,https://www.resrobot.se/,Europe/Stockholm,sv,NaN

In [17]:
trips = pd.read_csv(
    z.open("trips.txt"),
    dtype=str
)

print(trips.shape)
print(trips.columns.tolist())

(368048, 8)
['route_id', 'service_id', 'trip_id', 'trip_headsign', 'trip_short_name', 'direction_id', 'shape_id', 'samtrafiken_internal_trip_number']

In [18]:
trips = pd.read_csv(z.open("trips.txt"), dtype=str)
routes = pd.read_csv(z.open("routes.txt"), dtype=str)

print("trips:", trips.columns.tolist())
print("routes:", routes.columns.tolist())

trips: ['route_id', 'service_id', 'trip_id', 'trip_headsign', 'trip_short_name', 'direction_id', 'shape_id', 'samtrafiken_internal_trip_number']
routes: ['route_id', 'agency_id', 'route_short_name', 'route_long_name', 'route_type', 'route_desc']

In [19]:
trips_routes = trips.merge(
    routes[["route_id", "agency_id"]],
    on="route_id",
    how="left"
)

print(trips_routes.columns.tolist())

['route_id', 'service_id', 'trip_id', 'trip_headsign', 'trip_short_name', 'direction_id', 'shape_id', 'samtrafiken_internal_trip_number', 'agency_id']

In [20]:
wax_trips = trips_routes[
    trips_routes["agency_id"] == "505000000000000606"
]

print("Waxholms-trips:", len(wax_trips))

Waxholms-trips: 0

In [21]:
agency[
    agency["agency_name"].str.contains(
        "Waxholms", case=False, na=False
    )
]

,agency_id,agency_name,agency_url,agency_timezone,agency_lang,agency_fare_url
163,505000000000000606,Waxholmsbolaget Ångfartygs AB,https://www.resrobot.se/,Europe/Stockholm,sv,NaN

In [22]:
routes[
    routes["agency_id"].astype(str).str.contains(
        "505000000000000606",
        na=False
    )
]

Empty DataFrame
Columns: [route_id, agency_id, route_short_name, route_long_name, route_type, route_desc]
Index: []

In [23]:
trips.columns.tolist()

['route_id',
 'service_id',
 'trip_id',
 'trip_headsign',
 'trip_short_name',
 'direction_id',
 'shape_id',
 'samtrafiken_internal_trip_number']

In [24]:
vega = stops[
    stops["stop_name"].str.contains(
        "Vegabrygg", case=False, na=False
    )
][["stop_id", "stop_name"]]

vega

                stop_id    stop_name
12163             13092  Vegabryggan
88880  9022050013092001  Vegabryggan

In [25]:
stop_times = pd.read_csv(
    z.open("stop_times.txt"),
    dtype=str
)

trips = pd.read_csv(
    z.open("trips.txt"),
    dtype=str
)

print("stop_times:", stop_times.shape)
print("trips:", trips.shape)

stop_times: (8283082, 12)
trips: (368048, 8)

In [26]:
live_trips = df.merge(
    trips,
    on=["trip_id", "route_id"],
    how="left"
)

print("Live vehicles:", len(live_trips))

live_trips[
    [
        "vehicle_id",
        "trip_id",
        "route_id",
        "trip_headsign",
        "trip_short_name",
        "samtrafiken_internal_trip_number",
        "lat",
        "lon"
    ]
].head(100)

Live vehicles: 649

,vehicle_id,trip_id,route_id,trip_headsign,trip_short_name,samtrafiken_internal_trip_number,lat,lon
0,9031001001004806,14010000721637124,,NaN,NaN,NaN,59.308216,18.079399
1,9031001004505580,14010000729011536,,NaN,NaN,NaN,59.741592,18.599932
2,9031001003005037,14010000731930696,,NaN,NaN,NaN,59.228245,17.998379
3,9031001003005052,14010100731930960,,NaN,NaN,NaN,59.194607,18.189713
4,9031001007011770,14010000706740822,,NaN,NaN,NaN,59.342743,17.969767
...,...,...,...,...,...,...,...,...
95,9031001001004140,14010000694554312,,NaN,NaN,NaN,59.426048,17.959854
96,9031001004505506,14010000729243229,,NaN,NaN,NaN,59.392284,18.046757
97,9031001002500016,14010000702394987,,NaN,NaN,NaN,59.243076,18.094231
98,9031001006502916,,,NaN,NaN,NaN,59.626049,17.861244
99,9031001008000635,14010000684717435,,NaN,NaN,NaN,59.328869,18.084118

In [27]:
trips[
    trips["samtrafiken_internal_trip_number"].notna()
][[
    "trip_id",
    "route_id",
    "trip_headsign",
    "trip_short_name",
    "samtrafiken_internal_trip_number"
]].head(20)

,trip_id,route_id,trip_headsign,trip_short_name,samtrafiken_internal_trip_number
0,400000000000005073,9011001000000000,NaN,NaN,2200
1,400000000000005074,9011001000000000,NaN,NaN,2200
2,400000000000005077,9011001000000000,NaN,NaN,2200
3,400000000000005079,9011001000000000,NaN,NaN,2200
4,400000000000005080,9011001000000000,NaN,NaN,2200
5,400000000000005081,9011001000000000,NaN,NaN,2200
6,400000000000005084,9011001000000000,NaN,NaN,2200
7,400000000000005089,9011001000000000,NaN,NaN,2201
8,400000000000005090,9011001000000000,NaN,NaN,2201
9,400000000000005092,9011001000000000,NaN,NaN,2201
10,400000000000005110,9011001000000000,NaN,NaN,2203
11,400000000000005112,9011001000000000,NaN,NaN,2204
12,400000000000005114,9011001000000000,NaN,NaN,2204
13,400000000000005076,9011001000000000,NaN,NaN,2200
14,400000000000005083,9011001000000000,NaN,NaN,2200
15,400000000000005097,9011001000000000,NaN,NaN,2202
16,400000000000005099,9011001000000000,NaN,NaN,2202
17,400000000000005101,9011001000000000,NaN,NaN,2202
18,400000000000005105,9011001000000000,NaN,NaN,2203
19,400000000000005107,9011001000000000,NaN,NaN,2203

In [28]:
print("Live trips som finns i static:", len(live_trips))

Live trips som finns i static: 649

In [29]:
ferry_routes = routes[
    routes["route_type"].astype(str).str.strip() == "4"
]

print("Antal färjerutter:", len(ferry_routes))

ferry_routes[
    [
        "route_id",
        "agency_id",
        "route_short_name",
        "route_long_name",
        "route_type"
    ]
].head(100)

Antal färjerutter: 0

Empty DataFrame
Columns: [route_id, agency_id, route_short_name, route_long_name, route_type]
Index: []

In [30]:
print(routes.shape)
print(routes.dtypes)
print(routes.head())

(7323, 6)
route_id            object
agency_id           object
route_short_name    object
route_long_name     object
route_type          object
route_desc          object
dtype: object
              route_id           agency_id route_short_name route_long_name  \
0     9011001000000000  505000000000000001               40              SL
1  9011001000000000-41  505000000000000001               41              SL
2  9011001000000000-43  505000000000000001               43              SL
3  9011001000000000-48  505000000000000001               48              SL
4     9011001000100000  505000000000000001                1             NaN

  route_type route_desc
0        106        NaN
1        106        NaN
2        106        NaN
3        106        NaN
4        700        NaN

In [31]:
wax_routes = routes[
    routes["agency_id"] == "505000000000000606"
]

print("Waxholms routes:", len(wax_routes))

wax_routes[
    [
        "route_id",
        "route_short_name",
        "route_long_name",
        "route_type"
    ]
].head(100)

Waxholms routes: 0

Empty DataFrame
Columns: [route_id, route_short_name, route_long_name, route_type]
Index: []

In [32]:
live_trip_ids = set(df["trip_id"].dropna())

matched_trips = trips[
    trips["trip_id"].isin(live_trip_ids)
].copy()

print("Live trip_id som finns i static:", len(matched_trips))

Live trip_id som finns i static: 585

In [33]:
matched_trips[
    [
        "trip_id",
        "route_id",
        "trip_headsign",
        "trip_short_name",
        "direction_id",
        "samtrafiken_internal_trip_number"
    ]
].head(100)

,trip_id,route_id,trip_headsign,trip_short_name,direction_id,samtrafiken_internal_trip_number
1853,14010000733608097,9011001000100000,NaN,NaN,1,5015
1937,14010000733608216,9011001000100000,NaN,NaN,1,5016
2478,14010000733608135,9011001000100000,NaN,NaN,0,5176
2539,14010000733608288,9011001000100000,NaN,NaN,0,5178
3045,14010000697791805,9011001000200000,NaN,NaN,1,5341
...,...,...,...,...,...,...
18323,14010000688508787,9011001002900000,NaN,NaN,0,2212
18492,14010000706740822,9011001003000000,NaN,NaN,1,10828
18550,14010000706740647,9011001003000000,NaN,NaN,1,10758
18551,14010000706740720,9011001003000000,NaN,NaN,1,10813
18552,14010000706740896,9011001003000000,NaN,NaN,1,10843

In [34]:
wax_stop_names = stops[
    stops["stop_name"].str.contains(
        "brygga|bryggan",
        case=False,
        na=False
    )
][["stop_id", "stop_name"]]

wax_stop_names.head(100)

      stop_id                stop_name
749       858  Hälleviksstrands brygga
770       879          Rönnängs brygga
880      1020          Östersjö brygga
881      1021         Bromskärs brygga
894      1036            Hotellbryggan
...       ...                      ...
22980   24518       Björkholmen brygga
23164   24706         Järnaviks brygga
23193   24735     Ronneby Brunn brygga
23194   24736      Ronneby Hamn brygga
23195   24737       Ekenäs Karöbryggan

[100 rows x 2 columns]

In [35]:
live_trip_ids = set(df["trip_id"].dropna())

live_stop_times = stop_times[
    stop_times["trip_id"].isin(live_trip_ids)
].copy()

print("Live stop_times:", len(live_stop_times))

Live stop_times: 14229

In [36]:
live_stop_times = live_stop_times.merge(
    stops[["stop_id", "stop_name"]],
    on="stop_id",
    how="left"
)

live_stop_times[
    ["trip_id", "stop_id", "stop_name", "stop_sequence"]
].head(50)

              trip_id           stop_id            stop_name stop_sequence
0   14010000733608097  9022050001174002            Frihamnen             1
1   14010000733608097  9022050009915003       Frihamnsporten             2
2   14010000733608097  9022050010792002      Sehlstedtsgatan             3
3   14010000733608097  9022050009916002      Östhammarsgatan             4
4   14010000733608097  9022050009917002         Rökubbsgatan             5
5   14010000733608097  9022050009918002        Sandhamnsplan             6
6   14010000733608097  9022050012276001               Gärdet             7
7   14010000733608097  9022050012277002     Kampementsbacken             8
8   14010000733608097  9022050009943002       Storskärsgatan             9
9   14010000733608097  9022050012720001           Värtavägen            10
10  14010000733608097  9022050009912001         Jungfrugatan            11
11  14010000733608097  9022050011072002           Nybrogatan            12
12  14010000733608097  9022050009911001          Humlegården            13
13  14010000733608097  9022050009909002            Stureplan            14
14  14010000733608097  9022050011976002       Regeringsgatan            15
15  14010000733608097  9022050012808001             Hötorget            16
16  14010000733608097  9022050001541002       Cityterminalen            17
17  14010000733608097  9022050010790001         Kungsbroplan            18
18  14010000733608097  9022050012262001         Scheelegatan            19
19  14010000733608097  9022050012763001         Celsiusgatan            20
20  14010000733608097  9022050012224001       S:t Eriksgatan            21
21  14010000733608097  9022050009974006         Fridhemsplan            22
22  14010000733608097  9022050009987001      Mariebergsgatan            23
23  14010000733608097  9022050009996002  Fria Ukrainas plats            24
24  14010000733608097  9022050009994001       Wivalliusgatan            25
25  14010000733608097  9022050010815001       Lilla Essingen            26
26  14010000733608097  9022050009995001          Primusgatan            27
27  14010000733608097  9022050012825002            Broparken            28
28  14010000733608097  9022050010023001        Flottbrovägen            29
29  14010000733608097  9022050010025002        Essingetorget            30
30  14010000733608216  9022050001174002            Frihamnen             1
31  14010000733608216  9022050009915003       Frihamnsporten             2
32  14010000733608216  9022050010792002      Sehlstedtsgatan             3
33  14010000733608216  9022050009916002      Östhammarsgatan             4
34  14010000733608216  9022050009917002         Rökubbsgatan             5
35  14010000733608216  9022050009918002        Sandhamnsplan             6
36  14010000733608216  9022050012276001               Gärdet             7
37  14010000733608216  9022050012277002     Kampementsbacken             8
38  14010000733608216  9022050009943002       Storskärsgatan             9
39  14010000733608216  9022050012720001           Värtavägen            10
40  14010000733608216  9022050009912001         Jungfrugatan            11
41  14010000733608216  9022050011072002           Nybrogatan            12
42  14010000733608216  9022050009911001          Humlegården            13
43  14010000733608216  9022050009909002            Stureplan            14
44  14010000733608216  9022050011976002       Regeringsgatan            15
45  14010000733608216  9022050012808001             Hötorget            16
46  14010000733608216  9022050001541002       Cityterminalen            17
47  14010000733608216  9022050010790001         Kungsbroplan            18
48  14010000733608216  9022050012262001         Scheelegatan            19
49  14010000733608216  9022050012763001         Celsiusgatan            20

In [37]:
live_bryggor = live_stop_times[
    live_stop_times["stop_name"]
    .str.contains("brygga|bryggan", case=False, na=False)
]

print("Live trips med brygga:", live_bryggor["trip_id"].nunique())

Live trips med brygga: 49

In [38]:
live_bryggor_routes = (
    live_bryggor
    .merge(
        trips[["trip_id", "route_id"]],
        on="trip_id",
        how="left"
    )
    [["trip_id", "route_id"]]
    .drop_duplicates()
)

print("Antal routes:", len(live_bryggor_routes))

live_bryggor_routes["route_id"].value_counts().head(50)

Antal routes: 49

route_id
9011001070700000    5
9011001002100000    4
9011001005700000    4
9011001062600000    3
9011001071300000    3
9011001086500000    2
9011001074000000    2
9011001084600000    2
9011114001300000    2
9011114001400000    2
9011001043400000    2
9011114000900000    1
9011114000400000    1
9011114001200000    1
9011001084300000    1
9011001083900000    1
9011001078700000    1
9011001065200000    1
9011001063800000    1
9011001063700000    1
9011001063100000    1
9011001043800000    1
9011001043000000    1
9011001034000000    1
9011001031200000    1
9011001030300000    1
9011001023800000    1
9011001008000000    1
9011114002600000    1
Name: count, dtype: int64

In [39]:
boats_candidate = df[
    df["trip_id"].isin(live_bryggor["trip_id"])
].copy()

boats_candidate[
    ["vehicle_id", "trip_id", "route_id", "lat", "lon"]
].drop_duplicates()

           vehicle_id            trip_id route_id        lat        lon
2    9031001003005037  14010000731930696           59.228245  17.998379
15   9031001004505128  14010000729012315           59.727165  18.778692
20   9031001003002770  14010000695914221           59.212357  17.945473
40   9031001003005089  14010000731931014           59.144009  18.415688
66   9031001001004848  14010000731144231           59.357212  18.092955
71   9031001004505566  14010000729011678           59.780251  18.951906
101  9031001008000623  14010000694931017           59.399559  18.132586
106  9031001003005034  14010000734231963           59.274151  17.918579
109  9031001000500538  14010000729763510           59.422340  18.350983
119  9031001003005362  14010000691732772           59.240730  18.546436
165  9031001003005031  14010000698107785           59.118164  18.106518
180  9031001003005092  14010000704167082           59.122913  18.103661
203  9031001003002771  14010000676782039           59.211391  17.896088
207  9031001000500672  14010100725969298           59.325371  18.179592
211  9031001003002767  14010000702749493           59.269409  17.914246
219  9031001001508559  14010000729439045           59.340939  17.695551
221  9031001003005596  14010000676782495           59.210049  17.940662
235  9031001000500535  14010000729764514           59.374134  18.698526
254  9031001003001621  14010000702749602           59.226700  17.839619
259  9031001000500679  14010000728351827           59.321758  18.082712
265  9031001004505119  14010000729011875           60.047253  18.772381
302  9031001003001635  14010000674353818           59.260498  17.901106
308  9031001000500691  14010000729748445           59.396599  18.370317
328  9031001000500539  14010000729760525           59.348827  18.243561
373  9031001001507301  14010000709717800           59.360081  17.506121
379  9031001007011772  14010000696872794           59.358120  18.103909
389  9031001007011792  14010000696872838           59.361992  18.117626
396  9031001003002776  14010000685621404           59.213257  17.825895
410  9031001003002762  14010000674353919           59.225876  17.931110
417  9031001003006106  14010000624471461           59.198093  17.626940
450  9031001001004821  14010000731144147           59.310398  18.095604
485  9031001003003875  14010000677051076           59.307083  18.473528
501  9031001001004843  14010000731144420           59.312576  18.066092
509  9031001007011505  14010000693981652           59.356731  18.227921
511  9031001003002768  14010000685621605           59.276806  17.909899
512  9031001001004841  14010000717767493           59.358879  18.123026
519  9031001004505107  14010000729012540           59.819565  18.774553
536  9031001003002764  14010000685621205           59.200165  17.828238
543  9031001001508551  14010000729438886           59.289471  17.811541
552  9031001007011784  14010000696872815           59.356915  18.133093
564  9031001003003878  14010000707145651           59.307102  18.380051
565  9031001004505180  14010000732647570           59.487343  18.277185
584  9031001000500536  14010000729758704           59.357044  18.235376
604  9031001003003074  14010000704167447           59.097260  18.107862
608  9031001006500776  14010000719260536           59.373974  18.625334
611  9031001004505533  14010000729244683           59.487133  18.320217
612  9031001001004828  14010000731144332           59.330418  18.072924
633  9031001004505522  14010000729242070           59.496334  18.585817
647  9031001003005319  14010000715530544           59.355595  18.603558

In [40]:
boats_candidate[
    ["vehicle_id", "lat", "lon"]
].drop_duplicates().sort_values("lat")

           vehicle_id        lat        lon
604  9031001003003074  59.097260  18.107862
165  9031001003005031  59.118164  18.106518
180  9031001003005092  59.122913  18.103661
40   9031001003005089  59.144009  18.415688
417  9031001003006106  59.198093  17.626940
536  9031001003002764  59.200165  17.828238
221  9031001003005596  59.210049  17.940662
203  9031001003002771  59.211391  17.896088
20   9031001003002770  59.212357  17.945473
396  9031001003002776  59.213257  17.825895
410  9031001003002762  59.225876  17.931110
254  9031001003001621  59.226700  17.839619
2    9031001003005037  59.228245  17.998379
119  9031001003005362  59.240730  18.546436
302  9031001003001635  59.260498  17.901106
211  9031001003002767  59.269409  17.914246
106  9031001003005034  59.274151  17.918579
511  9031001003002768  59.276806  17.909899
543  9031001001508551  59.289471  17.811541
485  9031001003003875  59.307083  18.473528
564  9031001003003878  59.307102  18.380051
450  9031001001004821  59.310398  18.095604
501  9031001001004843  59.312576  18.066092
259  9031001000500679  59.321758  18.082712
207  9031001000500672  59.325371  18.179592
612  9031001001004828  59.330418  18.072924
219  9031001001508559  59.340939  17.695551
328  9031001000500539  59.348827  18.243561
647  9031001003005319  59.355595  18.603558
509  9031001007011505  59.356731  18.227921
552  9031001007011784  59.356915  18.133093
584  9031001000500536  59.357044  18.235376
66   9031001001004848  59.357212  18.092955
379  9031001007011772  59.358120  18.103909
512  9031001001004841  59.358879  18.123026
373  9031001001507301  59.360081  17.506121
389  9031001007011792  59.361992  18.117626
608  9031001006500776  59.373974  18.625334
235  9031001000500535  59.374134  18.698526
308  9031001000500691  59.396599  18.370317
101  9031001008000623  59.399559  18.132586
109  9031001000500538  59.422340  18.350983
611  9031001004505533  59.487133  18.320217
565  9031001004505180  59.487343  18.277185
633  9031001004505522  59.496334  18.585817
15   9031001004505128  59.727165  18.778692
71   9031001004505566  59.780251  18.951906
519  9031001004505107  59.819565  18.774553
265  9031001004505119  60.047253  18.772381

In [41]:
trip_info = trips[
    ["trip_id", "route_id", "trip_headsign", "trip_short_name", "direction_id"]
].rename(columns={"route_id": "static_route_id"})

boats_info = boats_candidate.merge(
    trip_info,
    on="trip_id",
    how="left"
)

boats_info[
    [
        "vehicle_id",
        "trip_id",
        "static_route_id",
        "trip_headsign",
        "trip_short_name",
        "lat",
        "lon"
    ]
].drop_duplicates().to_string(index=False)

'      vehicle_id           trip_id  static_route_id trip_headsign trip_short_name       lat       lon\n9031001003005037 14010000731930696 9011001086500000           NaN             NaN 59.228245 17.998379\n9031001004505128 14010000729012315 9011001063100000           NaN             NaN 59.727165 18.778692\n9031001003002770 14010000695914221 9011001071300000           NaN             NaN 59.212357 17.945473\n9031001003005089 14010000731931014 9011001083900000           NaN             NaN 59.144009 18.415688\n9031001001004848 14010000731144231 9011001005700000           NaN             NaN 59.357212 18.092955\n9031001004505566 14010000729011678 9011001063800000           NaN             NaN 59.780251 18.951906\n9031001008000623 14010000694931017 9011001008000000           NaN             NaN 59.399559 18.132586\n9031001003005034 14010000734231963 9011001086500000           NaN             NaN 59.274151 17.918579\n9031001000500538 14010000729763510 9011114001400000           NaN             NaN 59.422340 18.350983\n9031001003005362 14010000691732772 9011001043000000           NaN             NaN 59.240730 18.546436\n9031001003005031 14010000698107785 9011001084600000           NaN             NaN 59.118164 18.106518\n9031001003005092 14010000704167082 9011001084600000           NaN             NaN 59.122913 18.103661\n9031001003002771 14010000676782039 9011001071300000           NaN             NaN 59.211391 17.896088\n9031001000500672 14010100725969298 9011114002600000           NaN             NaN 59.325371 18.179592\n9031001003002767 14010000702749493 9011001070700000           NaN             NaN 59.269409 17.914246\n9031001001508559 14010000729439045 9011001034000000           NaN             NaN 59.340939 17.695551\n9031001003005596 14010000676782495 9011001071300000           NaN             NaN 59.210049 17.940662\n9031001000500535 14010000729764514 9011114001400000           NaN             NaN 59.374134 18.698526\n9031001003001621 14010000702749602 9011001070700000           NaN             NaN 59.226700 17.839619\n9031001000500679 14010000728351827 9011114000900000           NaN             NaN 59.321758 18.082712\n9031001004505119 14010000729011875 9011001063700000           NaN             NaN 60.047253 18.772381\n9031001003001635 14010000674353818 9011001074000000           NaN             NaN 59.260498 17.901106\n9031001000500691 14010000729748445 9011114000400000           NaN             NaN 59.396599 18.370317\n9031001000500539 14010000729760525 9011114001300000           NaN             NaN 59.348827 18.243561\n9031001001507301 14010000709717800 9011001031200000           NaN             NaN 59.360081 17.506121\n9031001007011772 14010000696872794 9011001002100000           NaN             NaN 59.358120 18.103909\n9031001007011792 14010000696872838 9011001002100000           NaN             NaN 59.361992 18.117626\n9031001003002776 14010000685621404 9011001070700000           NaN             NaN 59.213257 17.825895\n9031001003002762 14010000674353919 9011001074000000           NaN             NaN 59.225876 17.931110\n9031001003006106 14010000624471461 9011001078700000           NaN             NaN 59.198093 17.626940\n9031001001004821 14010000731144147 9011001005700000           NaN             NaN 59.310398 18.095604\n9031001003003875 14010000677051076 9011001043400000           NaN             NaN 59.307083 18.473528\n9031001001004843 14010000731144420 9011001005700000           NaN             NaN 59.312576 18.066092\n9031001007011505 14010000693981652 9011001002100000           NaN             NaN 59.356731 18.227921\n9031001003002768 14010000685621605 9011001070700000           NaN             NaN 59.276806 17.909899\n9031001001004841 14010000717767493 9011001023800000           NaN             NaN 59.358879 18.123026\n9031001004505107 14010000729012540 9011001065200000           NaN             NaN 59.819565 18.774553\n9031001003002764 14010000685621205 9011001070700000           NaN             NaN 59.200165 17.828238\n9031001001508551 14010000729438886 9011001030300000           NaN             NaN 59.289471 17.811541\n9031001007011784 14010000696872815 9011001002100000           NaN             NaN 59.356915 18.133093\n9031001003003878 14010000707145651 9011001043400000           NaN             NaN 59.307102 18.380051\n9031001004505180 14010000732647570 9011001062600000           NaN             NaN 59.487343 18.277185\n9031001000500536 14010000729758704 9011114001200000           NaN             NaN 59.357044 18.235376\n9031001003003074 14010000704167447 9011001084300000           NaN             NaN 59.097260 18.107862\n9031001006500776 14010000719260536 9011114001300000           NaN             NaN 59.373974 18.625334\n9031001004505533 14010000729244683 9011001062600000           NaN             NaN 59.487133 18.320217\n9031001001004828 14010000731144332 9011001005700000           NaN             NaN 59.330418 18.072924\n9031001004505522 14010000729242070 9011001062600000           NaN             NaN 59.496334 18.585817\n9031001003005319 14010000715530544 9011001043800000           NaN             NaN 59.355595 18.603558'

In [46]:
import folium

m = folium.Map(
    location=[
        boats_candidate["lat"].mean(),
        boats_candidate["lon"].mean()
    ],
    zoom_start=9
)

for _, row in boats_candidate.drop_duplicates(
    subset=["vehicle_id", "lat", "lon"]
).iterrows():

    popup_text = f"""
    vehicle_id: {row['vehicle_id']}<br>
    lat: {row['lat']}<br>
    lon: {row['lon']}<br>
    trip_id: {row['trip_id']}<br>
    route_id: {row['route_id']}
    """

    folium.Marker(
        location=[row["lat"], row["lon"]],
        popup=folium.Popup(
            popup_text,
            max_width=400
        )
    ).add_to(m)

m

In [47]:
import folium

m = folium.Map(
    location=[59.45, 18.5],
    zoom_start=9
)

# ALLA live vehicles
for _, row in df.drop_duplicates(
    subset=["vehicle_id", "lat", "lon"]
).iterrows():

    folium.CircleMarker(
        location=[row["lat"], row["lon"]],
        radius=2,
        popup=folium.Popup(
            f"""<pre>
vehicle_id: {row['vehicle_id']}
lat: {row['lat']}
lon: {row['lon']}
trip_id: {row['trip_id']}
route_id: {row['route_id']}
</pre>""",
            max_width=400
        )
    ).add_to(m)


# Våra nuvarande "brygga"-kandidater
for _, row in boats_candidate.drop_duplicates(
    subset=["vehicle_id", "lat", "lon"]
).iterrows():

    popup_text = f"""<pre>
vehicle_id: {row['vehicle_id']}
lat: {row['lat']}
lon: {row['lon']}
trip_id: {row['trip_id']}
route_id: {row['route_id']}
</pre>"""

    folium.Marker(
        location=[row["lat"], row["lon"]],
        popup=folium.Popup(
            popup_text,
            max_width=400
        ),
        tooltip=str(row["vehicle_id"])
    ).add_to(m)

m

In [48]:
south_svartso = df[
    (df["lat"] > 59.25) &
    (df["lat"] < 59.45) &
    (df["lon"] > 18.55) &
    (df["lon"] < 18.90)
].copy()

print("Antal fordon i området:", len(south_svartso))

south_svartso[
    ["vehicle_id", "trip_id", "route_id", "lat", "lon"]
].drop_duplicates().to_string(index=False)

Antal fordon i området: 6

'      vehicle_id           trip_id route_id       lat       lon\n9031001000500548 14010000729766473          59.282074 18.722553\n9031001000500535 14010000729764514          59.374134 18.698526\n9031001003005433 14010000684975211          59.323074 18.620592\n9031001006500776 14010000719260536          59.373974 18.625334\n9031001003005319 14010000715530544          59.355595 18.603558'

In [49]:
trip_id = "14010000729760525"

df[df["trip_id"].astype(str) == trip_id][
    ["vehicle_id", "trip_id", "route_id", "lat", "lon"]
]

           vehicle_id            trip_id route_id        lat        lon
328  9031001000500539  14010000729760525           59.348827  18.243561

In [50]:
trips[
    trips["trip_id"] == "14010000729760525"
]

,route_id,service_id,trip_id,trip_headsign,trip_short_name,direction_id,shape_id,samtrafiken_internal_trip_number
353093,9011114001300000,117,14010000729760525,NaN,NaN,1,6014010000729759725,1391

In [51]:
routes[
    routes["route_id"] == "9011114001300000"
]

,route_id,agency_id,route_short_name,route_long_name,route_type,route_desc
5298,9011114001300000,500000000000000114,13,NaN,1000,NaN

In [53]:
live_trips = df.merge(
    trips[["trip_id", "route_id"]],
    on="trip_id",
    how="inner",
    suffixes=("_live", "_static")
)

print(live_trips.columns.tolist())

['vehicle_id', 'vehicle_label', 'trip_id', 'route_id_live', 'lat', 'lon', 'current_stop_sequence', 'current_status', 'timestamp', 'route_id_static']

In [54]:
live_trips = live_trips.merge(
    routes[["route_id", "route_type", "route_short_name"]],
    left_on="route_id_static",
    right_on="route_id",
    how="left"
)

print(live_trips.columns.tolist())

['vehicle_id', 'vehicle_label', 'trip_id', 'route_id_live', 'lat', 'lon', 'current_stop_sequence', 'current_status', 'timestamp', 'route_id_static', 'route_id', 'route_type', 'route_short_name']

In [55]:
live_trips["route_type"].value_counts(dropna=False)

route_type
700     476
401      66
900      33
1000     23
Name: count, dtype: int64

In [56]:
boats = live_trips[
    live_trips["route_type"] == "1000"
].copy()

boats[
    ["vehicle_id", "trip_id", "route_id_static",
     "route_short_name", "lat", "lon"]
].drop_duplicates().to_string(index=False)

'      vehicle_id           trip_id      route_id_static route_short_name       lat       lon\n9031001007500531 14010000721404336     9011001008200000               82 59.320538 18.087587\n9031001008000750 14010000684717418     9011001008000000               80 59.320610 18.151686\n9031001008000635 14010000684717435     9011001008000000               80 59.328869 18.084118\n9031001008000623 14010000694931017     9011001008000000               80 59.399559 18.132586\n9031001000500538 14010000729763510     9011114001400000               14 59.422340 18.350983\n9031001000500548 14010000729766473     9011114001600000               16 59.282074 18.722553\n9031001000500672 14010100725969298     9011114002600000               26 59.325371 18.179592\n9031001008000630 14010000684717401     9011001008000000               80 59.351322 18.122866\n9031001008000634 14010000684717631     9011001008000000               80 59.343075 18.151892\n9031001000500535 14010000729764514     9011114001400000               14 59.374134 18.698526\n9031001000500679 14010000728351827     9011114000900000                9 59.321758 18.082712\n9031001000500691 14010000729748445     9011114000400000                4 59.396599 18.370317\n9031001000500539 14010000729760525     9011114001300000               13 59.348827 18.243561\n9031001008000627 14010000709992047     9011001008900000               89 59.299103 17.870937\n9031001000500554 14010000725968786     9011114002500000               25 59.651085 18.901133\n9031001008000628 14010000684717612     9011001008000000               80 59.317810 18.103350\n9031001000500519 14010000729769979     9011114002000000               20 59.129475 18.405382\n9031001008000625 14010000684717366 9011001008000000-80X              80X 59.327187 18.088318\n9031001000500683 14010100733922070     9011114002200000               22 58.885529 18.096842\n9031001000500680 14010000719256599     9011114000300000                3 59.355400 18.411793\n9031001000500520 14010000729768152     9011114001700000               17 59.193039 18.545881\n9031001000500536 14010000729758704     9011114001200000               12 59.357044 18.235376\n9031001006500776 14010000719260536     9011114001300000               13 59.373974 18.625334'

In [57]:
import folium

m = folium.Map(
    location=[59.45, 18.5],
    zoom_start=9
)

for _, row in boats.drop_duplicates(
    subset=["vehicle_id", "lat", "lon"]
).iterrows():

    popup_text = f"""<pre>
vehicle_id: {row['vehicle_id']}
trip_id: {row['trip_id']}
route_id: {row['route_id_static']}
route_short_name: {row['route_short_name']}
route_type: {row['route_type']}
lat: {row['lat']}
lon: {row['lon']}
</pre>"""

    folium.Marker(
        location=[row["lat"], row["lon"]],
        popup=folium.Popup(popup_text, max_width=450),
        tooltip=str(row["vehicle_id"])
    ).add_to(m)

m

In [52]:
# Koppla live vehicle till statisk trip
live_trips = df.merge(
    trips[["trip_id", "route_id"]],
    on="trip_id",
    how="inner"
)

# Koppla route_type
live_trips = live_trips.merge(
    routes[["route_id", "route_type", "route_short_name"]],
    on="route_id",
    how="left"
)

boats = live_trips[
    live_trips["route_type"] == "1000"
].copy()

print("Antal båtar:", len(boats))

boats[
    ["vehicle_id", "trip_id", "route_id",
     "route_short_name", "lat", "lon"]
].drop_duplicates().to_string(index=False)

KeyError: 'route_id'

In [43]:
import os
import requests

from google.transit import gtfs_realtime_pb2

API_KEY = os.environ["GTFSSweden3"]

URL = (
    "https://opendata.samtrafiken.se/gtfs-rt/sweden/VehiclePositions.pb"
    f"?key={API_KEY}"
)
URL = (
    "https://opendata.samtrafiken.se//gtfs-rt-sweden/{operator}/VehiclePositionsSweden.pb
    f"?key={API_KEY}"
)

r = requests.get(URL)
r.raise_for_status()

feed = gtfs_realtime_pb2.FeedMessage()
feed.ParseFromString(r.content)

count = 0

for entity in feed.entity:

    if not entity.HasField("vehicle"):
        continue

    v = entity.vehicle

    print("=" * 60)

    print("vehicle.id      :", v.vehicle.id)

    if v.vehicle.label:
        print("vehicle.label   :", v.vehicle.label)

    if v.vehicle.license_plate:
        print("license_plate   :", v.vehicle.license_plate)

    print("trip_id         :", v.trip.trip_id)
    print("route_id        :", v.trip.route_id)

    print("lat/lon         :", v.position.latitude, v.position.longitude)

    count += 1
    if count == 20:
        break
rows = []

for entity in feed.entity:

    if not entity.HasField("vehicle"):
        continue

    vehicle = entity.vehicle

    rows.append({

        "vehicle_id": vehicle.vehicle.id,

        "trip_id":
            vehicle.trip.trip_id
            if vehicle.HasField("trip") else None,

        "latitude":
            vehicle.position.latitude,

        "longitude":
            vehicle.position.longitude,

        "bearing":
            vehicle.position.bearing
            if vehicle.position.HasField("bearing") else None,

        "speed":
            vehicle.position.speed
            if vehicle.position.HasField("speed") else None,

        "timestamp":
            vehicle.timestamp

    })

samtrafiken = pd.DataFrame(rows)

SyntaxError: unterminated string literal (detected at line 13) (3530219695.py, line 13)

In [ ]:
from zipfile import ZipFile
import pandas as pd

with ZipFile("sweden_api.zip") as z:
    agencies = pd.read_csv(z.open("agency.txt"))

print(agencies)

In [ ]:
from zipfile import ZipFile
import pandas as pd

with ZipFile("sweden_api.zip") as z:
    agencies = pd.read_csv(z.open("agency.txt"))
    routes = pd.read_csv(z.open("routes.txt"))

# Leta efter Waxholmsbolaget
waxholm = agencies[
    agencies["agency_name"].str.contains("wax", case=False, na=False)
]

print(waxholm)

wax_routes = routes.merge(agencies, on="agency_id")

wax_routes = wax_routes[
    wax_routes["agency_name"].str.contains("wax", case=False, na=False)
]

print(wax_routes[[
    "route_id",
    "route_short_name",
    "route_long_name",
    "route_type",
    "agency_name"
]])

In [ ]:
from zipfile import ZipFile
import pandas as pd

with ZipFile("sweden_api.zip") as z:
    routes = pd.read_csv(z.open("routes.txt"))

print(routes.columns.tolist())

print("\nAntal routes:", len(routes))

print("\nAgency IDs som används:")

print(routes["agency_id"].value_counts())

In [ ]:
from zipfile import ZipFile
import pandas as pd

with ZipFile("sweden_api.zip") as z:
    agencies = pd.read_csv(z.open("agency.txt"))
    routes = pd.read_csv(z.open("routes.txt"))

routes = routes.merge(agencies, on="agency_id", how="left")

# Visa alla färjelinjer
ferries = routes[routes["route_type"] == 4]

print(f"Antal färjelinjer: {len(ferries)}")

print(
    ferries[
        [
            "agency_id",
            "agency_name",
            "route_id",
            "route_short_name",
            "route_long_name",
        ]
    ].head(50)
)

In [ ]:
from zipfile import ZipFile
import pandas as pd

with ZipFile("sweden_api.zip") as z:
    routes = pd.read_csv(z.open("routes.txt"))

print(routes["route_type"].value_counts().sort_index())

In [ ]:
from zipfile import ZipFile
import pandas as pd

with ZipFile("sweden_api.zip") as z:
    routes = pd.read_csv(z.open("routes.txt"))

for rt in sorted(routes.route_type.unique()):
    print("\n========== route_type", rt, "==========")
    cols = ["route_short_name", "route_long_name"]

    if "route_desc" in routes.columns:
        cols.append("route_desc")

    print(routes[routes.route_type == rt][cols].head(20).to_string(index=False))

In [ ]:
from zipfile import ZipFile
import pandas as pd

with ZipFile("sweden_api.zip") as z:
    routes = pd.read_csv(z.open("routes.txt"))

ferries = routes[routes.route_type == 1000]

print(ferries[[
    "route_id",
    "agency_id",
    "route_short_name",
    "route_long_name"
]].to_string(index=False))

In [ ]:
from zipfile import ZipFile
import pandas as pd

with ZipFile("sweden_api.zip") as z:
    agencies = pd.read_csv(z.open("agency.txt"))

print(
    agencies[
        agencies.agency_id == 500000000000000114
    ]
)

In [ ]:
from zipfile import ZipFile
import pandas as pd
from google.transit import gtfs_realtime_pb2

# ----- Läs GTFS static -----

with ZipFile("sweden_api.zip") as z:
    trips = pd.read_csv(
        z.open("trips.txt"),
        dtype={"trip_id": str, "route_id": str},
        low_memory=False,
    )

    routes = pd.read_csv(
        z.open("routes.txt"),
        dtype={"route_id": str},
    )

trips = trips[["trip_id", "route_id"]]
routes = routes[["route_id", "route_short_name", "route_long_name", "route_type"]]

# ----- Läs VehiclePositions -----

feed = gtfs_realtime_pb2.FeedMessage()

with open("VehiclePositions.pb", "rb") as f:
    feed.ParseFromString(f.read())

rows = []

for entity in feed.entity:

    if not entity.HasField("vehicle"):
        continue

    v = entity.vehicle
    rows.append({
        "vehicle_id": str(v.vehicle.id),
        "trip_id": str(v.trip.trip_id),
    })

vehicles = pd.DataFrame(rows)

# ----- Koppla ihop -----

df = (
    vehicles
      .merge(trips, on="trip_id", how="left")
      .merge(routes, on="route_id", how="left")
)

print(df.sort_values("route_short_name").head(200))

df.to_csv("vehicle_routes.csv", index=False)

In [ ]:
ferries = df[df["route_type"] == 1000].copy()

ferries = ferries.sort_values(["route_short_name", "vehicle_id"])

print(ferries[
    ["vehicle_id",
     "route_short_name",
     "route_id"]
])

ferries.to_csv("ferries.csv", index=False)

In [ ]:
route3 = ferries[ferries["route_short_name"] == "3"]
route3

In [ ]:
from zipfile import ZipFile
import pandas as pd

with ZipFile("sweden_api.zip") as z:
    stop_times = pd.read_csv(z.open("stop_times.txt"))

stop_times.head()

In [ ]:
trip_id = "14010000726426404"

trip = (
    stop_times[stop_times.trip_id == trip_id]
    .sort_values("stop_sequence")
)

trip

In [ ]:
with ZipFile("sweden_api.zip") as z:
    stops = pd.read_csv(z.open("stops.txt"))

stops.head()

In [ ]:
trip_stops = (
    stop_times
      .merge(stops, on="stop_id")
      .sort_values(["trip_id","stop_sequence"])
)

trip_stops.head(20)

In [ ]:
with ZipFile("sweden_api.zip") as z:
    trips = pd.read_csv(z.open("trips.txt"))
    routes = pd.read_csv(z.open("routes.txt"))

route3 = routes[routes.route_short_name=="3"]

route3

In [ ]:
print(stop_times.columns.tolist())
print(trips.columns.tolist())

In [ ]:
route3 = trips[trips.route_id == "9011114000300000"]

route3[
    [
        "trip_id",
        "trip_short_name",
        "samtrafiken_internal_trip_number",
        "service_id",
        "direction_id"
    ]
].sort_values(
    "samtrafiken_internal_trip_number"
)

In [ ]:
route3.to_csv("route3.csv")

In [ ]:
route3 = trips[trips["route_id"] == "9011114000300000"]

print("Trips:", len(route3))

route3[
    [
        "trip_id",
        "service_id",
        "direction_id",
        "trip_short_name",
        "samtrafiken_internal_trip_number"
    ]
].sort_values(
    ["direction_id", "samtrafiken_internal_trip_number"]
)

In [ ]:
trip305 = route3[
    route3["samtrafiken_internal_trip_number"] == 305
]

trip305

In [ ]:
trip_id = trip305.iloc[0]["trip_id"]

(
    stop_times[stop_times.trip_id == trip_id]
      .merge(
          stops[["stop_id", "stop_name"]],
          on="stop_id"
      )
      .sort_values("stop_sequence")
)[[
    "stop_sequence",
    "stop_name",
    "arrival_time",
    "pickup_booking_rule_id",
    "drop_off_booking_rule_id"
]]

In [ ]:
trip305 = (
    stop_times
      .query("trip_id == @trip_id")
      .merge(stops,on="stop_id")
      .sort_values("stop_sequence")
)

trip305

In [ ]:
trip305["pdf_flag"] = None

In [ ]:
with ZipFile("sweden_api.zip") as z: 
     files = sorted(z.namelist())
for f in files:
    if "booking" in f.lower():
        print(f)

In [ ]:
from zipfile import ZipFile
import pandas as pd

with ZipFile("sweden_api.zip") as z:
    booking_rules = pd.read_csv(z.open("booking_rules.txt"))

booking_rules.head(100)

In [ ]:
trip = (
    stop_times[stop_times.trip_id == trip_id]
      .merge(
          stops[["stop_id", "stop_name"]],
          on="stop_id"
      )
      .merge(
          booking_rules,
          left_on="pickup_booking_rule_id",
          right_on="booking_rule_id",
          how="left",
          suffixes=("","_pickup")
      )
      .sort_values("stop_sequence")
)

trip[
    [
        "stop_sequence",
        "stop_name",
        "arrival_time",
        "pickup_type",
        "pickup_booking_rule_id",
        "prior_notice_duration_min",
        "message"
    ]
]

In [ ]:
trip = (
    stop_times[stop_times.trip_id == trip_id]
      .merge(
          stops[["stop_id", "stop_name"]],
          on="stop_id"
      )
      .merge(
          booking_rules,
          left_on="pickup_booking_rule_id",
          right_on="booking_rule_id",
          how="left",
          suffixes=("","_pickup")
      )
      .sort_values("stop_sequence")
)

trip[
    [
        "stop_sequence",
        "stop_name",
        "arrival_time",
        "pickup_type",
        "pickup_booking_rule_id",
        "prior_notice_duration_min",
        "message"
    ]
]

In [ ]:
print(len(booking_rules))

In [ ]:
booking_rules[
    [
        "prior_notice_duration_min",
        "prior_notice_last_day",
        "prior_notice_last_time", 
        "phone_number"
    ]
].drop_duplicates()

In [ ]:
print("Antal olika regler",len(booking_rules[
    [
        "prior_notice_duration_min",
        "prior_notice_last_day",
        "prior_notice_last_time",
    ]
].drop_duplicates()))

In [ ]:
print("Antal olika regler",len(booking_rules[
    [
        "prior_notice_duration_min",
        "prior_notice_last_day",
        "prior_notice_last_time",
        "phone_number"
    ]
].drop_duplicates()))

In [ ]:
print("Antal olika regler",booking_rules.drop_duplicates())