## Analysera tidtabeller
* [#437](https://github.com/salgo60/Stockholm_Archipelago_Trail/issues/437)

In [2]:
from pathlib import Path
import requests
import pdfplumber
import pandas as pd
from tqdm.notebook import tqdm

In [5]:
BASE_URL = "https://kund.printhuset-sthlm.se/wa"

DOWNLOAD_DIR = Path("waxholm_pdf")
DOWNLOAD_DIR.mkdir(exist_ok=True)

routes = [str(i) for i in range(2, 32)] + [
    "40",
    "60a",
    "60b",
    "60d",
    "60e",
    "60f",
    "60g",
    "61",
    "65",
]

In [7]:
for route in tqdm(routes):

    url = f"{BASE_URL}/s{route}.pdf"

    filename = DOWNLOAD_DIR / f"s{route}.pdf"

    if filename.exists():
        continue

    r = requests.get(url)

    if r.status_code == 200:
        filename.write_bytes(r.content)
        print("Downloaded", filename.name)
    else:
        print("Missing", url)

  0%|          | 0/39 [00:00<?, ?it/s]

Missing https://kund.printhuset-sthlm.se/wa/s6.pdf
Missing https://kund.printhuset-sthlm.se/wa/s61.pdf
Missing https://kund.printhuset-sthlm.se/wa/s65.pdf

In [8]:
pdf = DOWNLOAD_DIR / "s3.pdf"

text = ""

with pdfplumber.open(pdf) as p:

    for page in p.pages:
        page_text = page.extract_text()

        if page_text:
            text += page_text + "\n"

print(text[:4000])

GÄLLER 19 JUNI 2026 – 16 AUGUSTI 2026 Uppdaterad 24 juni 2026
3A
STOCKHOLM – VAXHOLM – NORRA LAGNÖ – ÅLSTÄKET
DAG MÅNDAG–TORSDAG FREDAG
FARTYG
TURNUMMER
ANMÄRKNING
Strömkajen (Stockholm)
Slussen (Stockholm)
Nacka strand
Hasseludden
Gåshaga brygga
Vaxholm ank.
Vaxholm avg.
Grenadjärbryggan (Rindö)
Knutsholmen
Skogsö södra
Hästholmen
Skogsö udde
Norra Lagnö
Ålstäket
HELGTRAFIK ANSLUTANDE SL-TRAFIK
Vid jul, nyår, påsk, midsommar samt övriga storhelger Sök hela din resa på sl.se för att få tider för både
förekommer förändringar i trafiken. Se information anslutande SL-trafik och skärgårdstrafiken.
och sök din resa på waxholmsbolaget.se eller i appen.
NERAXAS
0303
06.28
06.45
ÖREVLIS
0300
06.45
07.00b
X
X
07.10
07.20
NEGGIV
0309
08.10
08.32
08.37b
X
X
08.47
08.55
09.10
TÅB-V
1401
07.45
08.00
08.10
ÖREVLIS
0320
08.15z
08.10z
08.50
NEGGIV
0309
09.32z
09.29z
09.26z
09.25z
08.55z
09.10
TÅB-V
1405
13.00
13.17
13.27
13.32
14.00
NEGGIV
0315
14.10
14.30
14.35b
X
X
14.45
14.55
15.10
TÅB-V
1305
17.00
17.03p
17.19
17.32
17.37
18.09
NEGGIV
0319
18.10
18.30
18.40b
X
X
18.50
19.00
19.15
ÖREBIV
0303
06.28
06.45
ÖREVLIS
0300
06.45
07.00b
X
X
07.10
07.20
NEGGIV
0309
08.10
08.32
08.37b
X
X
08.47
08.55
09.10
ÖDMRÄV
1421
07.45
08.00
08.10
ÖREVLIS
0320
08.15z
08.10z
08.50
NEGGIV
0309
09.32z
09.29z
09.26z
09.25z
08.55z
09.10
ÖXAV
1425
13.00
13.17
13.27
13.32
14.00
NEGGIV
0315
14.10
14.30
14.35b
X
X
14.45
14.55
15.10
ÖREBIV
1225
16.47
16.57
17.02
17.30
RÄKSROTS
0925
16.45
17.15
17.20
17.55
ANMÄRKNING BRYGGA OCH FARTYG
X Bryggorna trafikeras utan fast avgångstid.
| Bryggan trafikeras inte.
b Beställ resan i SL-appen, på
Waxholmsbolagets webb eller via kundtjänst
08-600 10 00 minst 1 timme innan avgång
från aktuell brygga, dock senast kl. 17.00.
p Endast påstigning.
z Bryggan trafikeras i omvänd ordning.
V-BÅT innebär att Värmdö, Vånö, Väddö, Viberö
eller Vaxö kör turen.
NEGGIV
0319
18.10
18.30
18.40b
X
X
18.50
19.00
19.15
GÄLLER 19 JUNI 2026 – 16 AUGUSTI 2026 Uppdaterad 24 juni 2026
3A
STOCKHOLM – VAXHOLM – NORRA LAGNÖ – ÅLSTÄKET
DAG LÖRDAG SÖNDAG
FARTYG
TURNUMMER
ANMÄRKNING
Strömkajen (Stockholm)
Slussen (Stockholm)
Nacka strand
Hasseludden
Gåshaga brygga
Vaxholm ank.
Vaxholm avg.
Knutsholmen
Skogsö södra
Hästholmen
Skogsö udde
Norra Lagnö
Ålstäket
HELGTRAFIK ANSLUTANDE SL-TRAFIK
Vid jul, nyår, påsk, midsommar samt övriga storhelger Sök hela din resa på sl.se för att få tider för både
förekommer förändringar i trafiken. Se information anslutande SL-trafik och skärgårdstrafiken.
och sök din resa på waxholmsbolaget.se eller i appen.
NEGGIV
0353
08.55
09.10b
X
X
09.20
09.30
ÖREBIV
1457
13.00
13.17
13.30
13.35
14.00
ÖREVLIS
0357
14.10
14.37b
X
X
14.47
15.00
ÖDMRÄV
1357
15.00
15.17
15.30
15.35
15.57
NEGGIV
0359
16.05
16.30b
X
X
16.40
17.00
NEGGIV
0373
08.35
09.05b
X
X
09.20
09.30
09.45
NEGALSOR
0975
15.00
15.17
15.28
15.33
15.58
NEGGIV
0379
16.00
16.30b
X
X
16.40
16.50
17.05
ÖRALAD
0875
17.10
17.45
17.50
18.22
ÖREVLIS
ANMÄRKNING BRYGGA
X Bryggorna trafikeras utan fast avgångstid.
| Bryggan trafikeras inte.
b Beställ resan i SL-appen, på
Waxholmsbolagets webb eller via kundtjänst
08-600 10 00 minst 1 timme innan avgång
från aktuell brygga, dock senast kl. 17.00.
0381
18.25
18.50b
X
X
19.00
19.10
GÄLLER 19 JUNI 2026 – 16 AUGUSTI 2026 Uppdaterad 24 juni 2026
3B
ÅLSTÄKET – NORRA LAGNÖ – VAXHOLM – STOCKHOLM
DAG MÅNDAG–TORSDAG
FARTYG
TURNUMMER
ANMÄRKNING
Ålstäket
Norra Lagnö
Skogsö udde
Hästholmen
Skogsö södra
Knutsholmen
Vaxholm ank.
Vaxholm avg.
Gåshaga brygga
Hasseludden
Nacka strand
Slussen (Stockholm)
Strömkajen (Stockholm)
HELGTRAFIK ANSLUTANDE SL-TRAFIK
Vid jul, nyår, påsk, midsommar samt övriga storhelger Sök hela din resa på sl.se för att få tider för både
förekommer förändringar i trafiken. Se information anslutande SL-trafik och skärgårdstrafiken.
och sök din resa på waxholmsbolaget.se eller i appen.
ÖREVLIS
0300
07.20z
07.10z
07.07z
07.05z
07.00bz
08.10
08.15
NEGALSOR
ÖREBIV
RELLE
0406
08.16
08.21
08.36
08.53a
08.56
ÖREVLIS
0306
08.50
09.37
NEGGIV
0308

In [9]:
documents = {}

for pdf in DOWNLOAD_DIR.glob("*.pdf"):

    txt = ""

    with pdfplumber.open(pdf) as p:

        for page in p.pages:

            t = page.extract_text()

            if t:
                txt += t + "\n"

    documents[pdf.stem] = txt

print(len(documents), "PDF loaded")

36 PDF loaded

In [10]:
import pdfplumber

pdf = DOWNLOAD_DIR / "s3.pdf"

with pdfplumber.open(pdf) as p:

    page = p.pages[0]

    tables = page.extract_tables()

print(f"{len(tables)} tables found")

1 tables found

In [12]:
table = tables[0]

for row in table[:20]:
    print(row)

import pandas as pd

df = pd.DataFrame(table)

print(df.shape)
df.head(20)

[None, 'MÅNDAG–TORSDAG', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
['FARTYG', 'NERAXAS', 'ÖREVLIS', 'NEGGIV', 'TÅB-V', None, 'ÖREVLIS', None, 'NEGGIV', 'TÅB-V', None, 'NEGGIV', 'TÅB-V', 'NEGGIV', 'ÖREBIV', 'ÖREVLIS', 'NEGGIV', 'ÖDMRÄV', None, 'ÖREVLIS', None, 'NEGGIV', 'ÖXAV', None, 'NEGGIV', 'ÖREBIV', 'RÄKSROTS', None]
['TURNUMMER', '0303', '0300', '0309', '1401', None, '0320', None, '0309', '1405', None, '0315', '1305', '0319', '0303', '0300', '0309', '1421', None, '0320', None, '0309', '1425', None, '0315', '1225', '0925', None]
['ANMÄRKNING', '', '', '', '', None, '', None, '', '', None, '', '', '', '', '', '', '', None, '', None, '', '', None, '', '', '', None]
[None, '', '', '', '07.45', None, '', None, '', '13.00', None, '', '17.00', '', '', '', '', '07.45', None, '', None, '', '13.00', None, '', '', '16.45', None]
[None, '', '', '', '', '', '', None, '', '', '', '', '17.03p', '', '', '', '', '', '', '', None, '', '', '', '', '', '', '']
[None, '', '', '', '08.00', None, '', None, '', '13.17', None, '', '17.19', '', '', '', '', '08.00', None, '', None, '', '13.17', None, '', '16.47', '', '']
[None, '', '', '', '08.10', None, '08.15z', None, '', '13.27', None, '', '17.32', '', '', '', '', '08.10', None, '08.15z', None, '', '13.27', None, '', '16.57', '17.15', None]
[None, '', '', '', '', None, '08.10z', None, '', '13.32', None, '', '17.37', '', '', '', '', '', None, '08.10z', None, '', '13.32', None, '', '17.02', '17.20', None]
[None, '', '', '', '', None, '', '', '', '14.00', None, '', '18.09', '', '', '', '', '', None, '', '', '', '14.00', None, '', '17.30', '17.55', None]
[None, '06.28', '', '08.10', '', None, '', '', '', '', None, '14.10', '', '18.10', '06.28', '', '08.10', '', None, '', '', '', '', None, '14.10', '', '', None]
[None, '06.45', '06.45', '08.32', '', None, '', '', '', '', None, '14.30', '', '18.30', '06.45', '06.45', '08.32', '', None, '', '', '', '', None, '14.30', '', '', None]
[None, '', '07.00b', '08.37b', '', None, '', '', '09.32z', '', None, '14.35b', '', '18.40b', '', '07.00b', '08.37b', '', None, '', '', '09.32z', '', None, '14.35b', '', '', None]
[None, '', 'X', 'X', '', None, '', '', '09.29z', '', None, 'X', '', 'X', '', 'X', 'X', '', None, '', '', '09.29z', '', None, 'X', '', '', None]
[None, '', 'X', 'X', '', None, '', '', '09.26z', '', None, 'X', '', 'X', '', 'X', 'X', '', None, '', '', '09.26z', '', None, 'X', '', '', None]
[None, '', '07.10', '08.47', '', None, '', '', '09.25z', '', None, '14.45', '', '18.50', '', '07.10', '08.47', '', None, '', '', '09.25z', '', None, '14.45', '', '', None]
[None, '', '07.20', '08.55', '', None, '08.50', None, '08.55z', '', None, '14.55', '', '19.00', '', '07.20', '08.55', '', None, '08.50', None, '08.55z', '', None, '14.55', '', '', None]
[None, '', '', '09.10', '', None, '', None, '09.10', '', None, '15.10', '', '19.15', '', '', '09.10', '', None, '', None, '09.10', '', None, '15.10', '', '', None]
(18, 28)

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,None,MÅNDAG–TORSDAG,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,FARTYG,NERAXAS,ÖREVLIS,NEGGIV,TÅB-V,None,ÖREVLIS,None,NEGGIV,TÅB-V,...,None,ÖREVLIS,None,NEGGIV,ÖXAV,None,NEGGIV,ÖREBIV,RÄKSROTS,None
2,TURNUMMER,0303,0300,0309,1401,None,0320,None,0309,1405,...,None,0320,None,0309,1425,None,0315,1225,0925,None
3,ANMÄRKNING,,,,,None,,None,,,...,None,,None,,,None,,,,None
4,None,,,,07.45,None,,None,,13.00,...,None,,None,,13.00,None,,,16.45,None
5,None,,,,,,,None,,,...,,,None,,,,,,,
6,None,,,,08.00,None,,None,,13.17,...,None,,None,,13.17,None,,16.47,,
7,None,,,,08.10,None,08.15z,None,,13.27,...,None,08.15z,None,,13.27,None,,16.57,17.15,None
8,None,,,,,None,08.10z,None,,13.32,...,None,08.10z,None,,13.32,None,,17.02,17.20,None
9,None,,,,,None,,,,14.00,...,None,,,,14.00,None,,17.30,17.55,None
10,None,06.28,,08.10,,None,,,,,...,None,,,,,None,14.10,,,None
11,None,06.45,06.45,08.32,,None,,,,,...,None,,,,,None,14.30,,,None
12,None,,07.00b,08.37b,,None,,,09.32z,,...,None,,,09.32z,,None,14.35b,,,None
13,None,,X,X,,None,,,09.29z,,...,None,,,09.29z,,None,X,,,None
14,None,,X,X,,None,,,09.26z,,...,None,,,09.26z,,None,X,,,None
15,None,,07.10,08.47,,None,,,09.25z,,...,None,,,09.25z,,None,14.45,,,None
16,None,,07.20,08.55,,None,08.50,None,08.55z,,...,None,08.50,None,08.55z,,None,14.55,,,None
17,None,,,09.10,,None,,None,09.10,,...,None,,None,09.10,,None,15.10,,,None

In [13]:
vessels = df.iloc[1]
turns   = df.iloc[2]
notes   = df.iloc[3]

meta = pd.DataFrame({
    "column": range(len(df.columns)),
    "vessel": vessels,
    "turn": turns,
    "note": notes
})

meta

    column    vessel       turn        note
0        0    FARTYG  TURNUMMER  ANMÄRKNING
1        1   NERAXAS       0303
2        2   ÖREVLIS       0300
3        3    NEGGIV       0309
4        4     TÅB-V       1401
5        5      None       None        None
6        6   ÖREVLIS       0320
7        7      None       None        None
8        8    NEGGIV       0309
9        9     TÅB-V       1405
10      10      None       None        None
11      11    NEGGIV       0315
12      12     TÅB-V       1305
13      13    NEGGIV       0319
14      14    ÖREBIV       0303
15      15   ÖREVLIS       0300
16      16    NEGGIV       0309
17      17    ÖDMRÄV       1421
18      18      None       None        None
19      19   ÖREVLIS       0320
20      20      None       None        None
21      21    NEGGIV       0309
22      22      ÖXAV       1425
23      23      None       None        None
24      24    NEGGIV       0315
25      25    ÖREBIV       1225
26      26  RÄKSROTS       0925
27      27      None       None        None

In [14]:
page = p.pages[0]

words = page.extract_words()

for w in words:
    print(w["text"])

GÄLLER
19
JUNI
2026
–
16
AUGUSTI
2026
Uppdaterad
24
juni
2026
3A
STOCKHOLM
–
VAXHOLM
–
NORRA
LAGNÖ
–
ÅLSTÄKET
DAG
MÅNDAG–TORSDAG
FREDAG
FARTYG
TURNUMMER
ANMÄRKNING
Strömkajen
(Stockholm)
Slussen
(Stockholm)
Nacka
strand
Hasseludden
Gåshaga
brygga
Vaxholm
ank.
Vaxholm
avg.
Grenadjärbryggan
(Rindö)
Knutsholmen
Skogsö
södra
Hästholmen
Skogsö
udde
Norra
Lagnö
Ålstäket
HELGTRAFIK
ANSLUTANDE
SL-TRAFIK
Vid
jul,
nyår,
påsk,
midsommar
samt
övriga
storhelger
Sök
hela
din
resa
på
sl.se
för
att
få
tider
för
både
förekommer
förändringar
i
trafiken.
Se
information
anslutande
SL-trafik
och
skärgårdstrafiken.
och
sök
din
resa
på
waxholmsbolaget.se
eller
i
appen.
NERAXAS
0303
06.28
06.45
ÖREVLIS
0300
06.45
07.00b
X
X
07.10
07.20
NEGGIV
0309
08.10
08.32
08.37b
X
X
08.47
08.55
09.10
TÅB-V
1401
07.45
08.00
08.10
ÖREVLIS
0320
08.15z
08.10z
08.50
NEGGIV
0309
09.32z
09.29z
09.26z
09.25z
08.55z
09.10
TÅB-V
1405
13.00
13.17
13.27
13.32
14.00
NEGGIV
0315
14.10
14.30
14.35b
X
X
14.45
14.55
15.10
TÅB-V
1305
17.00
17.03p
17.19
17.32
17.37
18.09
NEGGIV
0319
18.10
18.30
18.40b
X
X
18.50
19.00
19.15
ÖREBIV
0303
06.28
06.45
ÖREVLIS
0300
06.45
07.00b
X
X
07.10
07.20
NEGGIV
0309
08.10
08.32
08.37b
X
X
08.47
08.55
09.10
ÖDMRÄV
1421
07.45
08.00
08.10
ÖREVLIS
0320
08.15z
08.10z
08.50
NEGGIV
0309
09.32z
09.29z
09.26z
09.25z
08.55z
09.10
ÖXAV
1425
13.00
13.17
13.27
13.32
14.00
NEGGIV
0315
14.10
14.30
14.35b
X
X
14.45
14.55
15.10
ÖREBIV
1225
16.47
16.57
17.02
17.30
RÄKSROTS
0925
16.45
17.15
17.20
17.55
ANMÄRKNING
BRYGGA
OCH
FARTYG
X
Bryggorna
trafikeras
utan
fast
avgångstid.
|
Bryggan
trafikeras
inte.
b
Beställ
resan
i
SL-appen,
på
Waxholmsbolagets
webb
eller
via
kundtjänst
08-600
10
00
minst
1
timme
innan
avgång
från
aktuell
brygga,
dock
senast
kl.
17.00.
p
Endast
påstigning.
z
Bryggan
trafikeras
i
omvänd
ordning.
V-BÅT
innebär
att
Värmdö,
Vånö,
Väddö,
Viberö
eller
Vaxö
kör
turen.
NEGGIV
0319
18.10
18.30
18.40b
X
X
18.50
19.00
19.15

# Ny test

In [15]:
import requests
import pandas as pd

In [16]:
PIERS_URL = "https://map.stockholmarchipelagotrail.com/data/piers-identity.json"
VESSELS_URL = "https://map.stockholmarchipelagotrail.com/data/vessels-identity.json"

piers = requests.get(PIERS_URL).json()
vessels = requests.get(VESSELS_URL).json()

In [17]:
print(type(piers))
print(type(vessels))

print(len(piers))
print(len(vessels))

<class 'dict'>
<class 'dict'>
66
18

In [20]:
#list(piers.keys())  
print(type(piers))

first_key = next(iter(piers))

print(first_key)
print(piers[first_key])

<class 'dict'>
24hkr
{'uid': '24hkr', 'satId': 'sat:pier:24hkr', 'slug': 'alo', 'name': 'Ålö', 'concordances': {'gtfs': ['gtfs:9022001000224001'], 'slug': ['slug:alo']}, 'status': 'current', 'firstSeen': '2026-06-10'}

In [25]:
from unidecode import unidecode

def normalize(name):
    return (
        unidecode(name)
        .upper()
        .replace("-", " ")
        .replace("(", "")
        .replace(")", "")
        .strip()
    )

pier_lookup = {}

for pier in piers.values():
    key = normalize(pier["name"])
    pier_lookup[key] = pier
    print(key,pier)
#print(len(pier_lookup))

ALO {'uid': '24hkr', 'satId': 'sat:pier:24hkr', 'slug': 'alo', 'name': 'Ålö', 'concordances': {'gtfs': ['gtfs:9022001000224001'], 'slug': ['slug:alo']}, 'status': 'current', 'firstSeen': '2026-06-10'}
SANDHAMN {'uid': '25njf', 'satId': 'sat:pier:25njf', 'slug': 'sandhamn', 'name': 'Sandhamn', 'concordances': {'gtfs': ['gtfs:9022001000125001'], 'slug': ['slug:sandhamn']}, 'status': 'current', 'firstSeen': '2026-06-10'}
STROMKAJEN {'uid': '25rqy', 'satId': 'sat:pier:25rqy', 'slug': 'stromkajen', 'name': 'Strömkajen', 'concordances': {'gtfs': ['gtfs:9022001000301001', 'gtfs:9022001000301002', 'gtfs:9022001000301003', 'gtfs:9022001000301004', 'gtfs:9022001000301005', 'gtfs:9022001000301006', 'gtfs:9022001000301007', 'gtfs:9022001000301009', 'gtfs:9022001000301010', 'gtfs:9022001000301012', 'gtfs:9022001000301014', 'gtfs:9022001000301017'], 'slug': ['slug:stromkajen']}, 'status': 'current', 'firstSeen': '2026-06-10'}
LILLSVED {'uid': '2d2nq', 'satId': 'sat:pier:2d2nq', 'slug': 'lillsved', 'name': 'Lillsved', 'concordances': {'gtfs': ['gtfs:9022001000146001'], 'slug': ['slug:lillsved']}, 'status': 'current', 'firstSeen': '2026-06-10'}
GRANO {'uid': '3axkr', 'satId': 'sat:pier:3axkr', 'slug': 'grano', 'name': 'Granö', 'concordances': {'gtfs': ['gtfs:9022001000538001'], 'slug': ['slug:grano']}, 'status': 'current', 'firstSeen': '2026-06-10'}
BODA BRYGGA {'uid': '3k8k3', 'satId': 'sat:pier:3k8k3', 'slug': 'boda', 'name': 'Boda brygga', 'concordances': {'gtfs': ['gtfs:9022001000187001'], 'slug': ['slug:boda']}, 'status': 'current', 'firstSeen': '2026-06-10'}
LANDSORT {'uid': '3kwbd', 'satId': 'sat:pier:3kwbd', 'slug': 'landsort', 'name': 'Landsort', 'concordances': {'gtfs': ['gtfs:9022001000604001'], 'slug': ['slug:landsort']}, 'status': 'current', 'firstSeen': '2026-06-10'}
LANGVIK {'uid': '4whpf', 'satId': 'sat:pier:4whpf', 'slug': 'langvik-2', 'name': 'Långvik', 'concordances': {'gtfs': ['gtfs:9022001000183001'], 'slug': ['slug:langvik-2']}, 'status': 'current', 'firstSeen': '2026-06-10'}
VAXHOLM {'uid': '55sn9', 'satId': 'sat:pier:55sn9', 'slug': 'vaxholm', 'name': 'Vaxholm', 'concordances': {'gtfs': ['gtfs:9022001000401001', 'gtfs:9022001000401004', 'gtfs:9022001000401005', 'gtfs:9022001000401006', 'gtfs:9022001000401007', 'gtfs:9022001000401008', 'gtfs:9022001000401009', 'gtfs:9022001000401010', 'gtfs:9022001000401002'], 'slug': ['slug:vaxholm']}, 'status': 'current', 'firstSeen': '2026-06-10'}
ARHOLMA {'uid': '5cx6y', 'satId': 'sat:pier:5cx6y', 'slug': 'arholma', 'name': 'Arholma', 'concordances': {'gtfs': ['gtfs:9022001000539001'], 'slug': ['slug:arholma']}, 'status': 'current', 'firstSeen': '2026-06-10'}
SALTSJOBADEN {'uid': '5mca6', 'satId': 'sat:pier:5mca6', 'slug': 'saltsjobaden', 'name': 'Saltsjöbaden', 'concordances': {'gtfs': ['gtfs:9022001000901001'], 'slug': ['slug:saltsjobaden']}, 'status': 'current', 'firstSeen': '2026-06-10'}
KAPELLSKAR {'uid': '5qtk3', 'satId': 'sat:pier:5qtk3', 'slug': 'kapellskar', 'name': 'Kapellskär', 'concordances': {'gtfs': ['gtfs:9022001000532001'], 'slug': ['slug:kapellskar']}, 'status': 'current', 'firstSeen': '2026-06-10'}
SODERVIKEN {'uid': '65yhx', 'satId': 'sat:pier:65yhx', 'slug': 'soderviken', 'name': 'Söderviken', 'concordances': {'gtfs': ['gtfs:9022001000227001'], 'slug': ['slug:soderviken']}, 'status': 'current', 'firstSeen': '2026-06-10'}
STYRSVIK {'uid': '6w8v7', 'satId': 'sat:pier:6w8v7', 'slug': 'styrsvik', 'name': 'Styrsvik', 'concordances': {'gtfs': ['gtfs:9022001000102001'], 'slug': ['slug:styrsvik']}, 'status': 'current', 'firstSeen': '2026-06-10'}
GRADDO {'uid': '7ywpp', 'satId': 'sat:pier:7ywpp', 'slug': 'graddo', 'name': 'Gräddö', 'concordances': {'gtfs': ['gtfs:9022001000552001'], 'slug': ['slug:graddo']}, 'status': 'current', 'firstSeen': '2026-06-10'}
SOLLENKROKA {'uid': '88p26', 'satId': 'sat:pier:88p26', 'slug': 'sollenkroka', 'name': 'Sollenkroka', 'concordances': {'gtfs': ['gtfs:9022001000168001'], 'slug': ['slug:sollenkroka']}, 'status': 'current', 'firstSeen': '2026-06-10'}
NAMDOBOTE {'uid': '8a3zv', 'satId': 'sat:pier:8a3zv', 'slug': 'namdobote', 'name': 'Nämdöböte', 'concordances': {'gtfs': ['gtfs:9022001000103001'], 'slug': ['slug:namdobote']}, 'status': 'current', 'firstSeen': '2026-06-10'}
YXLO {'uid': '97dsz', 'satId': 'sat:pier:97dsz', 'slug': 'yxlo', 'name': 'Yxlö', 'concordances': {'gtfs': ['gtfs:9022001000514001'], 'slug': ['slug:yxlo']}, 'status': 'current', 'firstSeen': '2026-06-10'}
GRUVBRYGGAN {'uid': '9d4ts', 'satId': 'sat:pier:9d4ts', 'slug': 'gruvbryggan', 'name': 'Gruvbryggan', 'concordances': {'gtfs': ['gtfs:9022001000202001'], 'slug': ['slug:gruvbryggan']}, 'status': 'current', 'firstSeen': '2026-06-10'}
RAFSNAS {'uid': 'a9st3', 'satId': 'sat:pier:a9st3', 'slug': 'rafsnas', 'name': 'Räfsnäs', 'concordances': {'gtfs': ['gtfs:9022001000541001'], 'slug': ['slug:rafsnas']}, 'status': 'current', 'firstSeen': '2026-06-10'}
NORRA GRINDA {'uid': 'ana8w', 'satId': 'sat:pier:ana8w', 'slug': 'norra-grinda', 'name': 'Norra Grinda', 'concordances': {'gtfs': ['gtfs:9022001000148001'], 'slug': ['slug:norra-grinda']}, 'status': 'current', 'firstSeen': '2026-06-10'}
KOPMANHOLM {'uid': 'badnq', 'satId': 'sat:pier:badnq', 'slug': 'kopmanholm', 'name': 'Köpmanholm', 'concordances': {'gtfs': ['gtfs:9022001000515001'], 'slug': ['slug:kopmanholm']}, 'status': 'current', 'firstSeen': '2026-06-10'}
FINNHAMN {'uid': 'bg8n2', 'satId': 'sat:pier:bg8n2', 'slug': 'finnhamn', 'name': 'Finnhamn', 'concordances': {'gtfs': ['gtfs:9022001000824001'], 'slug': ['slug:finnhamn']}, 'status': 'current', 'firstSeen': '2026-06-10'}
LANGVIK {'uid': 'bks6e', 'satId': 'sat:pier:bks6e', 'slug': 'langvik', 'name': 'Långvik', 'concordances': {'gtfs': ['gtfs:9022001000119001'], 'slug': ['slug:langvik']}, 'status': 'current', 'firstSeen': '2026-06-10'}
SODRA GRINDA {'uid': 'c2zdb', 'satId': 'sat:pier:c2zdb', 'slug': 'sodra-grinda', 'name': 'Södra Grinda', 'concordances': {'gtfs': ['gtfs:9022001000147001'], 'slug': ['slug:sodra-grinda']}, 'status': 'current', 'firstSeen': '2026-06-10'}
VASTANVIK {'uid': 'c6pn8', 'satId': 'sat:pier:c6pn8', 'slug': 'vastanvik', 'name': 'Västanvik', 'concordances': {'gtfs': ['gtfs:9022001000108001'], 'slug': ['slug:vastanvik']}, 'status': 'current', 'firstSeen': '2026-06-10'}
LOKA {'uid': 'cg6tm', 'satId': 'sat:pier:cg6tm', 'slug': 'loka', 'name': 'Löka', 'concordances': {'gtfs': ['gtfs:9022001000181001'], 'slug': ['slug:loka']}, 'status': 'current', 'firstSeen': '2026-06-10'}
NORRTALJE {'uid': 'cjh66', 'satId': 'sat:pier:cjh66', 'slug': 'norrtalje', 'name': 'Norrtälje', 'concordances': {'gtfs': ['gtfs:9022001000554001'], 'slug': ['slug:norrtalje']}, 'status': 'current', 'firstSeen': '2026-06-10'}
SPRANGA {'uid': 'd9x33', 'satId': 'sat:pier:d9x33', 'slug': 'spranga', 'name': 'Spränga', 'concordances': {'gtfs': ['gtfs:9022001000204001'], 'slug': ['slug:spranga']}, 'status': 'current', 'firstSeen': '2026-06-10'}
NORRA SVARTSO {'uid': 'dz2kk', 'satId': 'sat:pier:dz2kk', 'slug': 'norra-svartso', 'name': 'Norra Svartsö', 'concordances': {'gtfs': ['gtfs:9022001000150001'], 'slug': ['slug:norra-svartso']}, 'status': 'current', 'firstSeen': '2026-06-10'}
ANKARUDDEN {'uid': 'exbtj', 'satId': 'sat:pier:exbtj', 'slug': 'ankarudden', 'name': 'Ankarudden', 'concordances': {'gtfs': ['gtfs:9022001000602001'], 'slug': ['slug:ankarudden']}, 'status': 'current', 'firstSeen': '2026-06-10'}
ALSVIK {'uid': 'fb4m2', 'satId': 'sat:pier:fb4m2', 'slug': 'alsvik', 'name': 'Alsvik', 'concordances': {'gtfs': ['gtfs:9022001000153001'], 'slug': ['slug:alsvik']}, 'status': 'current', 'firstSeen': '2026-06-10'}
BUNKVIK {'uid': 'fvpsd', 'satId': 'sat:pier:fvpsd', 'slug': 'bunkvik', 'name': 'Bunkvik', 'concordances': {'gtfs': ['gtfs:9022001000112001'], 'slug': ['slug:bunkvik']}, 'status': 'current', 'firstSeen': '2026-06-10'}
OSTERSJO {'uid': 'fxdp4', 'satId': 'sat:pier:fxdp4', 'slug': 'ostersjo', 'name': 'Östersjö', 'concordances': {'gtfs': ['gtfs:9022001000537001'], 'slug': ['slug:ostersjo']}, 'status': 'current', 'firstSeen': '2026-06-10'}
NATTARO {'uid': 'g9c6x', 'satId': 'sat:pier:g9c6x', 'slug': 'nattaro', 'name': 'Nåttarö', 'concordances': {'gtfs': ['gtfs:9022001000220001'], 'slug': ['slug:nattaro']}, 'status': 'current', 'firstSeen': '2026-06-10'}
ORNOBODA {'uid': 'gj722', 'satId': 'sat:pier:gj722', 'slug': 'ornoboda', 'name': 'Ornöboda', 'concordances': {'gtfs': ['gtfs:9022001000226001'], 'slug': ['slug:ornoboda']}, 'status': 'current', 'firstSeen': '2026-06-10'}
SKALVIK {'uid': 'h3e32', 'satId': 'sat:pier:h3e32', 'slug': 'skalvik', 'name': 'Skälvik', 'concordances': {'gtfs': ['gtfs:9022001000156001'], 'slug': ['slug:skalvik']}, 'status': 'current', 'firstSeen': '2026-06-10'}
FJARDLANG {'uid': 'h5e27', 'satId': 'sat:pier:h5e27', 'slug': 'fjardlang', 'name': 'Fjärdlång', 'concordances': {'gtfs': ['gtfs:9022001000231001'], 'slug': ['slug:fjardlang']}, 'status': 'current', 'firstSeen': '2026-06-10'}
SAND {'uid': 'h5sec', 'satId': 'sat:pier:h5sec', 'slug': 'sand', 'name': 'Sand', 'concordances': {'gtfs': ['gtfs:9022001000111001'], 'slug': ['slug:sand']}, 'status': 'current', 'firstSeen': '2026-06-10'}
STAVSNAS {'uid': 'hdd6b', 'satId': 'sat:pier:hdd6b', 'slug': 'stavsnas', 'name': 'Stavsnäs', 'concordances': {'gtfs': ['gtfs:9022001000101001'], 'slug': ['slug:stavsnas']}, 'status': 'current', 'firstSeen': '2026-06-10'}
LATTINGE {'uid': 'hk4c2', 'satId': 'sat:pier:hk4c2', 'slug': 'lattinge', 'name': 'Lättinge', 'concordances': {'gtfs': ['gtfs:9022001000218001'], 'slug': ['slug:lattinge']}, 'status': 'current', 'firstSeen': '2026-06-10'}
NASUDDEN {'uid': 'hv928', 'satId': 'sat:pier:hv928', 'slug': 'nasudden', 'name': 'Näsudden', 'concordances': {'gtfs': ['gtfs:9022001000203001'], 'slug': ['slug:nasudden']}, 'status': 'current', 'firstSeen': '2026-06-10'}
SOLVIK {'uid': 'jz4b2', 'satId': 'sat:pier:jz4b2', 'slug': 'solvik', 'name': 'Solvik', 'concordances': {'gtfs': ['gtfs:9022001000109001'], 'slug': ['slug:solvik']}, 'status': 'current', 'firstSeen': '2026-06-10'}
DALARO {'uid': 'k3ga2', 'satId': 'sat:pier:k3ga2', 'slug': 'dalaro', 'name': 'Dalarö', 'concordances': {'gtfs': ['gtfs:9022001000209001'], 'slug': ['slug:dalaro']}, 'status': 'current', 'firstSeen': '2026-06-10'}
KOLSVIK {'uid': 'kcqca', 'satId': 'sat:pier:kcqca', 'slug': 'kolsvik', 'name': 'Kolsvik', 'concordances': {'gtfs': ['gtfs:9022001000510001'], 'slug': ['slug:kolsvik']}, 'status': 'current', 'firstSeen': '2026-06-10'}
BROTTO {'uid': 'mb7mm', 'satId': 'sat:pier:mb7mm', 'slug': 'brotto', 'name': 'Brottö', 'concordances': {'gtfs': ['gtfs:9022001000826001'], 'slug': ['slug:brotto']}, 'status': 'current', 'firstSeen': '2026-06-10'}
SODRA INGMARSO {'uid': 'npv3h', 'satId': 'sat:pier:npv3h', 'slug': 'sodra-ingmarso', 'name': 'Södra Ingmarsö', 'concordances': {'gtfs': ['gtfs:9022001000827001'], 'slug': ['slug:sodra-ingmarso']}, 'status': 'current', 'firstSeen': '2026-06-10'}
LIDO {'uid': 'ptqk8', 'satId': 'sat:pier:ptqk8', 'slug': 'lido', 'name': 'Lidö', 'concordances': {'gtfs': ['gtfs:9022001000534001'], 'slug': ['slug:lido']}, 'status': 'current', 'firstSeen': '2026-06-10'}
NORRA INGMARSO {'uid': 'r9h6s', 'satId': 'sat:pier:r9h6s', 'slug': 'norra-ingmarso', 'name': 'Norra Ingmarsö', 'concordances': {'gtfs': ['gtfs:9022001000823001'], 'slug': ['slug:norra-ingmarso']}, 'status': 'current', 'firstSeen': '2026-06-10'}
ORNO KYRKA {'uid': 'r9t9s', 'satId': 'sat:pier:r9t9s', 'slug': 'orno-kyrka', 'name': 'Ornö kyrka', 'concordances': {'gtfs': ['gtfs:9022001000230001'], 'slug': ['slug:orno-kyrka']}, 'status': 'current', 'firstSeen': '2026-06-10'}
OSTANVIK {'uid': 'rt7xw', 'satId': 'sat:pier:rt7xw', 'slug': 'ostanvik', 'name': 'Östanvik', 'concordances': {'gtfs': ['gtfs:9022001000106001'], 'slug': ['slug:ostanvik']}, 'status': 'current', 'firstSeen': '2026-06-10'}
FURUSUND {'uid': 'syrra', 'satId': 'sat:pier:syrra', 'slug': 'furusund', 'name': 'Furusund', 'concordances': {'gtfs': ['gtfs:9022001000525001'], 'slug': ['slug:furusund']}, 'status': 'current', 'firstSeen': '2026-06-10'}
KALKBERGET {'uid': 'tnjrd', 'satId': 'sat:pier:tnjrd', 'slug': 'kalkberget', 'name': 'Kalkberget', 'concordances': {'gtfs': ['gtfs:9022001000107001'], 'slug': ['slug:kalkberget']}, 'status': 'current', 'firstSeen': '2026-06-10'}
RANO {'uid': 'vmgj9', 'satId': 'sat:pier:vmgj9', 'slug': 'rano', 'name': 'Rånö', 'concordances': {'gtfs': ['gtfs:9022001000223001'], 'slug': ['slug:rano']}, 'status': 'current', 'firstSeen': '2026-06-10'}
NYNASHAMN {'uid': 'w9mqf', 'satId': 'sat:pier:w9mqf', 'slug': 'nynashamn', 'name': 'Nynäshamn', 'concordances': {'gtfs': ['gtfs:9022001000601001'], 'slug': ['slug:nynashamn']}, 'status': 'current', 'firstSeen': '2026-06-10'}
SODERBOUDD {'uid': 'wcghw', 'satId': 'sat:pier:wcghw', 'slug': 'soderboudd', 'name': 'Söderboudd', 'concordances': {'gtfs': ['gtfs:9022001000161001'], 'slug': ['slug:soderboudd']}, 'status': 'current', 'firstSeen': '2026-06-10'}
ARSTA {'uid': 'x224j', 'satId': 'sat:pier:x224j', 'slug': 'arsta', 'name': 'Årsta', 'concordances': {'gtfs': ['gtfs:9022001000201001'], 'slug': ['slug:arsta']}, 'status': 'current', 'firstSeen': '2026-06-10'}
ASATTRA {'uid': 'x9mp5', 'satId': 'sat:pier:x9mp5', 'slug': 'asattra', 'name': 'Åsättra', 'concordances': {'gtfs': ['gtfs:9022001000829001'], 'slug': ['slug:asattra']}, 'status': 'current', 'firstSeen': '2026-06-10'}
FURUSUND {'uid': 'x9t5q', 'satId': 'sat:pier:x9t5q', 'slug': 'furusund-2', 'name': 'Furusund', 'concordances': {'gtfs': ['gtfs:9022001000525001'], 'slug': ['slug:furusund-2']}, 'status': 'current', 'firstSeen': '2026-06-10'}
BERG {'uid': 'xqdpx', 'satId': 'sat:pier:xqdpx', 'slug': 'berg', 'name': 'Berg', 'concordances': {'gtfs': ['gtfs:9022001000180001'], 'slug': ['slug:berg']}, 'status': 'current', 'firstSeen': '2026-06-10'}
BROKHOLMEN {'uid': 'y2b5e', 'satId': 'sat:pier:y2b5e', 'slug': 'brokholmen', 'name': 'Brokholmen', 'concordances': {'gtfs': ['gtfs:9022001000503001'], 'slug': ['slug:brokholmen']}, 'status': 'current', 'firstSeen': '2026-06-10'}
RAMSMORA {'uid': 'y7y66', 'satId': 'sat:pier:y7y66', 'slug': 'ramsmora', 'name': 'Ramsmora', 'concordances': {'gtfs': ['gtfs:9022001000182001'], 'slug': ['slug:ramsmora']}, 'status': 'current', 'firstSeen': '2026-06-10'}
MOJASTROM {'uid': 'yd6px', 'satId': 'sat:pier:yd6px', 'slug': 'mojastrom', 'name': 'Möjaström', 'concordances': {'gtfs': ['gtfs:9022001000179001'], 'slug': ['slug:mojastrom']}, 'status': 'current', 'firstSeen': '2026-06-10'}
SIMPNAS {'uid': 'z8knr', 'satId': 'sat:pier:z8knr', 'slug': 'simpnas', 'name': 'Simpnäs', 'concordances': {'gtfs': ['gtfs:9022001000540001'], 'slug': ['slug:simpnas']}, 'status': 'current', 'firstSeen': '2026-06-10'}
HASSELMARA {'uid': 'zqjp7', 'satId': 'sat:pier:zqjp7', 'slug': 'hasselmara', 'name': 'Hässelmara', 'concordances': {'gtfs': ['gtfs:9022001000215001'], 'slug': ['slug:hasselmara']}, 'status': 'current', 'firstSeen': '2026-06-10'}
GATAN {'uid': 'zw4s7', 'satId': 'sat:pier:zw4s7', 'slug': 'gatan', 'name': 'Gatan', 'concordances': {'gtfs': ['gtfs:9022001000118001'], 'slug': ['slug:gatan']}, 'status': 'current', 'firstSeen': '2026-06-10'}

In [26]:
gtfs_to_sat = {}

for pier in piers.values():
    for gtfs in pier.get("concordances", {}).get("gtfs", []):
        gtfs_to_sat[gtfs] = pier["satId"]

print(len(gtfs_to_sat))

84

In [28]:
import re
from unidecode import unidecode

def normalize(text):
    if text is None:
        return None

    text = unidecode(str(text))
    text = text.upper()
    text = text.replace("(", "")
    text = text.replace(")", "")
    text = text.replace("-", " ")
    text = re.sub(r"\s+", " ", text)

    return text.strip()


TIME_RE = re.compile(r"^(\d\d)\.(\d\d)([abpz]?)$")


def parse_time(value):

    if value is None:
        return None

    value = value.strip()

    if value == "":
        return None

    if value == "X":
        return {
            "flexStop": True
        }

    m = TIME_RE.match(value)

    if not m:
        return {
            "raw": value
        }

    hh, mm, flag = m.groups()

    return {
        "time": f"{hh}:{mm}",
        "bookingRequired": flag == "b",
        "dropoffOnly": flag == "a",
        "pickupOnly": flag == "p",
        "reverseOrder": flag == "z"
    }

In [29]:
tests = [
    "07.00b",
    "08.53a",
    "17.03p",
    "09.32z",
    "14.10",
    "X"
]

for t in tests:
    print(t, "->", parse_time(t))

07.00b -> {'time': '07:00', 'bookingRequired': True, 'dropoffOnly': False, 'pickupOnly': False, 'reverseOrder': False}
08.53a -> {'time': '08:53', 'bookingRequired': False, 'dropoffOnly': True, 'pickupOnly': False, 'reverseOrder': False}
17.03p -> {'time': '17:03', 'bookingRequired': False, 'dropoffOnly': False, 'pickupOnly': True, 'reverseOrder': False}
09.32z -> {'time': '09:32', 'bookingRequired': False, 'dropoffOnly': False, 'pickupOnly': False, 'reverseOrder': True}
14.10 -> {'time': '14:10', 'bookingRequired': False, 'dropoffOnly': False, 'pickupOnly': False, 'reverseOrder': False}
X -> {'flexStop': True}

In [30]:
vessels = df.iloc[1]
turns = df.iloc[2]

trips = []

for col in range(len(df.columns)):

    vessel = vessels[col]
    trip = turns[col]

    if vessel is None:
        continue

    vessel = vessel.strip()

    if vessel == "":
        continue

    trips.append({
        "column": col,
        "vessel": vessel,
        "trip": trip
    })

len(trips)

21

In [31]:
pd.DataFrame(trips)

    column    vessel       trip
0        0    FARTYG  TURNUMMER
1        1   NERAXAS       0303
2        2   ÖREVLIS       0300
3        3    NEGGIV       0309
4        4     TÅB-V       1401
5        6   ÖREVLIS       0320
6        8    NEGGIV       0309
7        9     TÅB-V       1405
8       11    NEGGIV       0315
9       12     TÅB-V       1305
10      13    NEGGIV       0319
11      14    ÖREBIV       0303
12      15   ÖREVLIS       0300
13      16    NEGGIV       0309
14      17    ÖDMRÄV       1421
15      19   ÖREVLIS       0320
16      21    NEGGIV       0309
17      22      ÖXAV       1425
18      24    NEGGIV       0315
19      25    ÖREBIV       1225
20      26  RÄKSROTS       0925

In [32]:
ROUTES = {

    "3A": [
        "Strömkajen",
        "Slussen",
        "Nacka strand",
        "Hasseludden",
        "Gåshaga brygga",
        "Vaxholm ank.",
        "Vaxholm avg.",
        "Grenadjärbryggan",
        "Knutsholmen",
        "Skogsö södra",
        "Hästholmen",
        "Skogsö udde",
        "Norra Lagnö",
        "Ålstäket"
    ]
}

# Ny start